# This file has been generated by node2nix 1.11.1. Do not edit!
{
  nodeEnv,
  fetchurl,
  fetchgit,
  nix-gitignore,
  stdenv,
  lib,
  globalBuildInputs ? [],
}: let
  sources = {
    "Base64-0.1.4" = {
      name = "Base64";
      packageName = "Base64";
      version = "0.1.4";
      src = fetchurl {
        url = "https://registry.npmjs.org/Base64/-/Base64-0.1.4.tgz";
        sha512 = "rHuyFTuK3/IH8tMcDB0BVrfpVM8+YQ7XSsICoYUu+JUUjnbbSyPfHok/NWLFgUbKt8sPeOIEFX6YJJTO2vgt7w==";
      };
    };
    "JSONStream-0.4.4" = {
      name = "JSONStream";
      packageName = "JSONStream";
      version = "0.4.4";
      src = fetchurl {
        url = "https://registry.npmjs.org/JSONStream/-/JSONStream-0.4.4.tgz";
        sha512 = "0PZdD2nQCa76Q+So8SX6au7v19Bp4veBTqD91kqfJiYPhG0uwumVmz0PBcwFfXDeVlN7JjlgHbAZejUvfUBzBQ==";
      };
    };
    "JSONStream-0.6.4" = {
      name = "JSONStream";
      packageName = "JSONStream";
      version = "0.6.4";
      src = fetchurl {
        url = "https://registry.npmjs.org/JSONStream/-/JSONStream-0.6.4.tgz";
        sha512 = "ER8YVJ+Xk4a1g+d8Xq9RFe2rjsUHV9eSRqfwe9DS5J5ga8bKWx4FwXZNWXpGDYchuOfqf4NFmDlwuloqHIj/5A==";
      };
    };
    "abbrev-1.1.1" = {
      name = "abbrev";
      packageName = "abbrev";
      version = "1.1.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/abbrev/-/abbrev-1.1.1.tgz";
        sha512 = "nne9/IiQ/hzIhY6pdDnbBtz7DjPTKrY00P/zvPSm5pOFkl6xuGrGnXn/VtTNNfNtAfZ9/1RtehkszU9qcTii0Q==";
      };
    };
    "amdefine-1.0.1" = {
      name = "amdefine";
      packageName = "amdefine";
      version = "1.0.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/amdefine/-/amdefine-1.0.1.tgz";
        sha512 = "S2Hw0TtNkMJhIabBwIojKL9YHO5T0n5eNqWJ7Lrlel/zDbftQpxpapi8tZs3X1HWa+u+QeydGmzzNU0m09+Rcg==";
      };
    };
    "ansi-styles-4.3.0" = {
      name = "ansi-styles";
      packageName = "ansi-styles";
      version = "4.3.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/ansi-styles/-/ansi-styles-4.3.0.tgz";
        sha512 = "zbB9rCJAT1rbjiVDb2hqKFHNYLxgtk8NURxZ3IZwD3F6NtxbXZQCnnSi1Lkx+IDohdPlFp222wVALIheZJQSEg==";
      };
    };
    "argparse-1.0.10" = {
      name = "argparse";
      packageName = "argparse";
      version = "1.0.10";
      src = fetchurl {
        url = "https://registry.npmjs.org/argparse/-/argparse-1.0.10.tgz";
        sha512 = "o5Roy6tNG4SL/FOkCAN6RzjiakZS25RLYFrcMttJqbdd8BWrnA+fGz57iN5Pb06pvBGvl5gQ0B48dJlslXvoTg==";
      };
    };
    "array-each-1.0.1" = {
      name = "array-each";
      packageName = "array-each";
      version = "1.0.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/array-each/-/array-each-1.0.1.tgz";
        sha512 = "zHjL5SZa68hkKHBFBK6DJCTtr9sfTCPCaph/L7tMSLcTFgy+zX7E+6q5UArbtOtMBCtxdICpfTCspRse+ywyXA==";
      };
    };
    "array-slice-1.1.0" = {
      name = "array-slice";
      packageName = "array-slice";
      version = "1.1.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/array-slice/-/array-slice-1.1.0.tgz";
        sha512 = "B1qMD3RBP7O8o0H2KbrXDyB0IccejMF15+87Lvlor12ONPRHP6gTjXMNkt/d3ZuOGbAe66hFmaCfECI24Ufp6w==";
      };
    };
    "astw-0.0.0" = {
      name = "astw";
      packageName = "astw";
      version = "0.0.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/astw/-/astw-0.0.0.tgz";
        sha512 = "1U7z5mTBIkFRMXG+ujTN9dPRVIb+LPk18Du32JLP7gdZqtDILyVQvyflb7BNJf4R5GQxNPcJl45A2vs6Ouu+3A==";
      };
    };
    "async-0.2.10" = {
      name = "async";
      packageName = "async";
      version = "0.2.10";
      src = fetchurl {
        url = "https://registry.npmjs.org/async/-/async-0.2.10.tgz";
        sha512 = "eAkdoKxU6/LkKDBzLpT+t6Ff5EtfSF4wx1WfJiPEEV7WNLnDaRXk0oVysiEPm262roaachGexwUv94WhSgN5TQ==";
      };
    };
    "async-2.6.4" = {
      name = "async";
      packageName = "async";
      version = "2.6.4";
      src = fetchurl {
        url = "https://registry.npmjs.org/async/-/async-2.6.4.tgz";
        sha512 = "mzo5dfJYwAn29PeiJ0zvwTo04zj8HDJj0Mn8TD7sno7q12prdbnasKJHhkm2c1LgrhlJ0teaea8860oxi51mGA==";
      };
    };
    "async-3.2.4" = {
      name = "async";
      packageName = "async";
      version = "3.2.4";
      src = fetchurl {
        url = "https://registry.npmjs.org/async/-/async-3.2.4.tgz";
        sha512 = "iAB+JbDEGXhyIUavoDl9WP/Jj106Kz9DEn1DPgYw5ruDn0e3Wgi3sKFm55sASdGBNOQB8F59d9qQ7deqrHA8wQ==";
      };
    };
    "balanced-match-1.0.2" = {
      name = "balanced-match";
      packageName = "balanced-match";
      version = "1.0.2";
      src = fetchurl {
        url = "https://registry.npmjs.org/balanced-match/-/balanced-match-1.0.2.tgz";
        sha512 = "3oSeUO0TMV67hN1AmbXsK4yaqU7tjiHlbxRDZOpH0KW9+CeX4bRAaX0Anxt0tx2MrpRpWwQaPwIlISEJhYU5Pw==";
      };
    };
    "base64-js-0.0.2" = {
      name = "base64-js";
      packageName = "base64-js";
      version = "0.0.2";
      src = fetchurl {
        url = "https://registry.npmjs.org/base64-js/-/base64-js-0.0.2.tgz";
        sha512 = "Pj9L87dCdGcKlSqPVUjD+q96pbIx1zQQLb2CUiWURfjiBELv84YX+0nGnKmyT/9KkC7PQk7UN1w+Al8bBozaxQ==";
      };
    };
    "base64-js-0.0.8" = {
      name = "base64-js";
      packageName = "base64-js";
      version = "0.0.8";
      src = fetchurl {
        url = "https://registry.npmjs.org/base64-js/-/base64-js-0.0.8.tgz";
        sha512 = "3XSA2cR/h/73EzlXXdU6YNycmYI7+kicTxks4eJg2g39biHR84slg2+des+p7iHYhbRg/udIS4TD53WabcOUkw==";
      };
    };
    "bluebird-3.7.2" = {
      name = "bluebird";
      packageName = "bluebird";
      version = "3.7.2";
      src = fetchurl {
        url = "https://registry.npmjs.org/bluebird/-/bluebird-3.7.2.tgz";
        sha512 = "XpNj6GDQzdfW+r2Wnn7xiSAd7TM3jzkxGXBGTtWKuSXv1xUV+azxAm8jdWZN06QTQk+2N2XB9jRDkvbmQmcRtg==";
      };
    };
    "body-5.1.0" = {
      name = "body";
      packageName = "body";
      version = "5.1.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/body/-/body-5.1.0.tgz";
        sha512 = "chUsBxGRtuElD6fmw1gHLpvnKdVLK302peeFa9ZqAEk8TyzZ3fygLyUEDDPTJvL9+Bor0dIwn6ePOsRM2y0zQQ==";
      };
    };
    "bops-0.0.6" = {
      name = "bops";
      packageName = "bops";
      version = "0.0.6";
      src = fetchurl {
        url = "https://registry.npmjs.org/bops/-/bops-0.0.6.tgz";
        sha512 = "EWD8/Ei9o/h/wmR3w/YL/8dGKe4rSFHlaO8VNNcuXnjXjeTgxdcmhjPf9hRCYlqTrBPZbKaht+FxZKahcob5UQ==";
      };
    };
    "brace-expansion-1.1.11" = {
      name = "brace-expansion";
      packageName = "brace-expansion";
      version = "1.1.11";
      src = fetchurl {
        url = "https://registry.npmjs.org/brace-expansion/-/brace-expansion-1.1.11.tgz";
        sha512 = "iCuPHDFgrHX7H2vEI/5xpz07zSHB00TpugqhmYtVmMO6518mCuRMoOYFldEBl0g187ufozdaHgWKcYFb61qGiA==";
      };
    };
    "braces-3.0.2" = {
      name = "braces";
      packageName = "braces";
      version = "3.0.2";
      src = fetchurl {
        url = "https://registry.npmjs.org/braces/-/braces-3.0.2.tgz";
        sha512 = "b8um+L1RzM3WDSzvhm6gIz1yfTbBt6YTlcEKAvsmqCZZFw46z626lVj9j1yEPW33H5H+lBQpZMP1k8l+78Ha0A==";
      };
    };
    "browser-builtins-2.0.5" = {
      name = "browser-builtins";
      packageName = "browser-builtins";
      version = "2.0.5";
      src = fetchurl {
        url = "https://registry.npmjs.org/browser-builtins/-/browser-builtins-2.0.5.tgz";
        sha512 = "VtXesABnxtG6xk/By2yI7BaIEorZhEy9TnFDh89PxQWZp8fb+x5BnPVtoERl//Ph6O88ojUsEW2NfBbWkmfHvA==";
      };
    };
    "browser-filesaver-1.1.1" = {
      name = "browser-filesaver";
      packageName = "browser-filesaver";
      version = "1.1.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/browser-filesaver/-/browser-filesaver-1.1.1.tgz";
        sha512 = "UI4ps3bE/YXvGKlL7BoITvw8bE/SOt7YnvZeCyME7votTLxsDQ0ES0lvQdEWZMvO9aF5/66h+a3PGWn1KOblBA==";
      };
    };
    "browser-pack-1.1.0" = {
      name = "browser-pack";
      packageName = "browser-pack";
      version = "1.1.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/browser-pack/-/browser-pack-1.1.0.tgz";
        sha512 = "4hn+XOI1o0HnwZ0LYt/ekUGY5UlJDjOCEsDSXFNz+qiFIw4xlb1hce7PBnOdqYzz7vmMWWRShneEuMBa9JW0ow==";
      };
    };
    "browser-resolve-1.2.4" = {
      name = "browser-resolve";
      packageName = "browser-resolve";
      version = "1.2.4";
      src = fetchurl {
        url = "https://registry.npmjs.org/browser-resolve/-/browser-resolve-1.2.4.tgz";
        sha512 = "z8CRZZEv/MVAuJ9u9/LwzAcGswFtWbdAHh8f8ZkHgThUb88rBZbpwoxYZaQnmbAxvCoOA1gFIONrspStOhldkg==";
      };
    };
    "browserify-2.36.1" = {
      name = "browserify";
      packageName = "browserify";
      version = "2.36.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/browserify/-/browserify-2.36.1.tgz";
        sha512 = "hMtdYssPUnetEssn8BToIfPD3y0DS+loAybh5lzlrLiUUnmYUpjmDAfeShlKzvyCbxbYzsXQiUIv+DfELJ0Jcw==";
      };
    };
    "buffer-browserify-0.2.5" = {
      name = "buffer-browserify";
      packageName = "buffer-browserify";
      version = "0.2.5";
      src = fetchurl {
        url = "https://registry.npmjs.org/buffer-browserify/-/buffer-browserify-0.2.5.tgz";
        sha512 = "3ko6TTBwXb15w2OgZuyAzLJwUFClBMvcKcmhF+iQ79G71K8Fc3RqKzroCN0a0DbZw2GM3q9lNoqfYYCTq6w7QA==";
      };
    };
    "bytes-1.0.0" = {
      name = "bytes";
      packageName = "bytes";
      version = "1.0.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/bytes/-/bytes-1.0.0.tgz";
        sha512 = "/x68VkHLeTl3/Ll8IvxdwzhrT+IyKc52e/oyHhA2RwqPqswSnjVbSddfPRwAsJtbilMAPSRWwAlpxdYsSWOTKQ==";
      };
    };
    "call-bind-1.0.2" = {
      name = "call-bind";
      packageName = "call-bind";
      version = "1.0.2";
      src = fetchurl {
        url = "https://registry.npmjs.org/call-bind/-/call-bind-1.0.2.tgz";
        sha512 = "7O+FbCihrB5WGbFYesctwmTKae6rOiIzmz1icreWJ+0aA7LJfuqhEso2T9ncpcFtzMQtzXf2QGGueWJGTYsqrA==";
      };
    };
    "callsite-1.0.0" = {
      name = "callsite";
      packageName = "callsite";
      version = "1.0.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/callsite/-/callsite-1.0.0.tgz";
        sha512 = "0vdNRFXn5q+dtOqjfFtmtlI9N2eVZ7LMyEV2iKC5mEEFvSg/69Ml6b/WU2qF8W1nLRa0wiSrDT3Y5jOHZCwKPQ==";
      };
    };
    "camelcase-1.2.1" = {
      name = "camelcase";
      packageName = "camelcase";
      version = "1.2.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/camelcase/-/camelcase-1.2.1.tgz";
        sha512 = "wzLkDa4K/mzI1OSITC+DUyjgIl/ETNHE9QvYgy6J6Jvqyyz4C0Xfd+lQhb19sX2jMpZV4IssUn0VDVmglV+s4g==";
      };
    };
    "chalk-4.1.2" = {
      name = "chalk";
      packageName = "chalk";
      version = "4.1.2";
      src = fetchurl {
        url = "https://registry.npmjs.org/chalk/-/chalk-4.1.2.tgz";
        sha512 = "oKnbhFyRIXpUuez8iBMmyEa4nbj4IOQyuhc/wy9kY7/WVPcwIO9VA668Pu8RkO7+0G76SLROeyw9CpQ061i4mA==";
      };
    };
    "cli-1.0.1" = {
      name = "cli";
      packageName = "cli";
      version = "1.0.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/cli/-/cli-1.0.1.tgz";
        sha512 = "41U72MB56TfUMGndAKK8vJ78eooOD4Z5NOL4xEfjc0c23s+6EYKXlXsmACBVclLP1yOfWCgEganVzddVrSNoTg==";
      };
    };
    "color-convert-2.0.1" = {
      name = "color-convert";
      packageName = "color-convert";
      version = "2.0.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/color-convert/-/color-convert-2.0.1.tgz";
        sha512 = "RRECPsj7iu/xb5oKYcsFHSppFNnsj/52OVTRKb4zP5onXwVF3zVmmToNcOfGC+CRDpfK/U584fMg38ZHCaElKQ==";
      };
    };
    "color-name-1.1.4" = {
      name = "color-name";
      packageName = "color-name";
      version = "1.1.4";
      src = fetchurl {
        url = "https://registry.npmjs.org/color-name/-/color-name-1.1.4.tgz";
        sha512 = "dOy+3AuW3a2wNbZHIuMZpTcgjGuLU/uBL/ubcZF9OXbDo8ff4O8yVp5Bf0efS8uEoYo5q4Fx7dY9OgQGXgAsQA==";
      };
    };
    "colors-1.1.2" = {
      name = "colors";
      packageName = "colors";
      version = "1.1.2";
      src = fetchurl {
        url = "https://registry.npmjs.org/colors/-/colors-1.1.2.tgz";
        sha512 = "ENwblkFQpqqia6b++zLD/KUWafYlVY/UNnAp7oz7LY7E924wmpye416wBOmvv/HMWzl8gL1kJlfvId/1Dg176w==";
      };
    };
    "combine-source-map-0.3.0" = {
      name = "combine-source-map";
      packageName = "combine-source-map";
      version = "0.3.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/combine-source-map/-/combine-source-map-0.3.0.tgz";
        sha512 = "HRKa6g9SC1xd6ifto8ay6SxvyHaaQ50/8NO1ZONXx2hsIF9t/52qXa7Eeivaf5KFOSowK7Nm8TkIL/VC4khdBA==";
      };
    };
    "commondir-0.0.2" = {
      name = "commondir";
      packageName = "commondir";
      version = "0.0.2";
      src = fetchurl {
        url = "https://registry.npmjs.org/commondir/-/commondir-0.0.2.tgz";
        sha512 = "s4oS0jIUZ1t1LJCN7MI2cEDEd25cCSEW0vluKuDEsYcR0KGIiX7HmTtPMbxqGlaqGaihsGlmko1P3vNWzV7cOg==";
      };
    };
    "concat-map-0.0.1" = {
      name = "concat-map";
      packageName = "concat-map";
      version = "0.0.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/concat-map/-/concat-map-0.0.1.tgz";
        sha512 = "/Srv4dswyQNBfohGpz9o6Yb3Gz3SrUDqBH5rTuhGR7ahtlbYKnVxw2bCFMRljaA7EXHaXZ8wsHdodFvbkhKmqg==";
      };
    };
    "concat-stream-1.0.1" = {
      name = "concat-stream";
      packageName = "concat-stream";
      version = "1.0.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/concat-stream/-/concat-stream-1.0.1.tgz";
        sha512 = "nAHFsgeRVVvZ+aB3S1gLeN73fQ+tdOcw075BHbXMbC6MY0h6nqAkEeqPVCw8kRuDJJZDvaUjxI4jZv2FD0Tl8A==";
      };
    };
    "console-browserify-1.0.3" = {
      name = "console-browserify";
      packageName = "console-browserify";
      version = "1.0.3";
      src = fetchurl {
        url = "https://registry.npmjs.org/console-browserify/-/console-browserify-1.0.3.tgz";
        sha512 = "mIy/TXtcNHCzckiUr4f8m9MSQkG2rjvtI7QAK5vM7VdSlCjZqsoYUkcx9NaLEFuKBYJqd5+hLKj/YCo33heXOQ==";
      };
    };
    "console-browserify-1.1.0" = {
      name = "console-browserify";
      packageName = "console-browserify";
      version = "1.1.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/console-browserify/-/console-browserify-1.1.0.tgz";
        sha512 = "duS7VP5pvfsNLDvL1O4VOEbw37AI3A4ZUQYemvDlnpGrNu9tprR7BYWpDYwC0Xia0Zxz5ZupdiIrUp0GH1aXfg==";
      };
    };
    "constants-browserify-0.0.1" = {
      name = "constants-browserify";
      packageName = "constants-browserify";
      version = "0.0.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/constants-browserify/-/constants-browserify-0.0.1.tgz";
        sha512 = "FL+diDS9AKR5BAA2M+GNk8lnH64tRE3zepTG9hucxc7o04LgCRhkQZhF7u/OKHZT8LLRT+sZEi9qFzXUchq9pA==";
      };
    };
    "continuable-cache-0.3.1" = {
      name = "continuable-cache";
      packageName = "continuable-cache";
      version = "0.3.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/continuable-cache/-/continuable-cache-0.3.1.tgz";
        sha512 = "TF30kpKhTH8AGCG3dut0rdd/19B7Z+qCnrMoBLpyQu/2drZdNrrpcjPEoJeSVsQM+8KmWG5O56oPDjSSUsuTyA==";
      };
    };
    "convert-source-map-0.3.5" = {
      name = "convert-source-map";
      packageName = "convert-source-map";
      version = "0.3.5";
      src = fetchurl {
        url = "https://registry.npmjs.org/convert-source-map/-/convert-source-map-0.3.5.tgz";
        sha512 = "+4nRk0k3oEpwUB7/CalD7xE2z4VmtEnnq0GO2IPTkrooTrAhEsWvuLF5iWP1dXrwluki/azwXV1ve7gtYuPldg==";
      };
    };
    "copy-anything-2.0.6" = {
      name = "copy-anything";
      packageName = "copy-anything";
      version = "2.0.6";
      src = fetchurl {
        url = "https://registry.npmjs.org/copy-anything/-/copy-anything-2.0.6.tgz";
        sha512 = "1j20GZTsvKNkc4BY3NpMOM8tt///wY3FpIzozTOFO2ffuZcV61nojHXVKIy3WM+7ADCy5FVhdZYHYDdgTU0yJw==";
      };
    };
    "core-util-is-1.0.3" = {
      name = "core-util-is";
      packageName = "core-util-is";
      version = "1.0.3";
      src = fetchurl {
        url = "https://registry.npmjs.org/core-util-is/-/core-util-is-1.0.3.tgz";
        sha512 = "ZQBvi1DcpJ4GDqanjucZ2Hj3wEO5pZDS89BWbkcrvdxksJorwUDDZamX9ldFkp9aw2lmBDLgkObEA4DWNJ9FYQ==";
      };
    };
    "crypto-browserify-1.0.9" = {
      name = "crypto-browserify";
      packageName = "crypto-browserify";
      version = "1.0.9";
      src = fetchurl {
        url = "https://registry.npmjs.org/crypto-browserify/-/crypto-browserify-1.0.9.tgz";
        sha512 = "fWmkaZPmccreTmANMdpvI0UrF34pzTAZDLKDcF0n5ThwpyeAs+DtSVxyhrZc6kHFiOFdyzjW5uZ8jAWE3kNY6A==";
      };
    };
    "date-now-0.1.4" = {
      name = "date-now";
      packageName = "date-now";
      version = "0.1.4";
      src = fetchurl {
        url = "https://registry.npmjs.org/date-now/-/date-now-0.1.4.tgz";
        sha512 = "AsElvov3LoNB7tf5k37H2jYSB+ZZPMT5sG2QjJCcdlV5chIv6htBUBUui2IKRjgtKAKtCBN7Zbwa+MtwLjSeNw==";
      };
    };
    "dateformat-3.0.3" = {
      name = "dateformat";
      packageName = "dateformat";
      version = "3.0.3";
      src = fetchurl {
        url = "https://registry.npmjs.org/dateformat/-/dateformat-3.0.3.tgz";
        sha512 = "jyCETtSl3VMZMWeRo7iY1FL19ges1t55hMo5yaam4Jrsm5EPL89UQkoQRyiI+Yf4k8r2ZpdngkV8hr1lIdjb3Q==";
      };
    };
    "debug-3.2.7" = {
      name = "debug";
      packageName = "debug";
      version = "3.2.7";
      src = fetchurl {
        url = "https://registry.npmjs.org/debug/-/debug-3.2.7.tgz";
        sha512 = "CFjzYYAi4ThfiQvizrFQevTTXHtnCqWfe7x1AhgEscTz6ZbLbfoLRLPugTQyBth6f8ZERVUSyWHFD/7Wu4t1XQ==";
      };
    };
    "decamelize-1.2.0" = {
      name = "decamelize";
      packageName = "decamelize";
      version = "1.2.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/decamelize/-/decamelize-1.2.0.tgz";
        sha512 = "z2S+W9X73hAUUki+N+9Za2lBlun89zigOyGrsax+KUQ6wKW4ZoWpEYBkGhQjwAjjDCkWxhY0VKEhk8wzY7F5cA==";
      };
    };
    "deep-equal-0.0.0" = {
      name = "deep-equal";
      packageName = "deep-equal";
      version = "0.0.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/deep-equal/-/deep-equal-0.0.0.tgz";
        sha512 = "p1bI/kkDPT6auUI0U+WLuIIrzmDIDo80I406J8tT4y6I4ZGtBuMeTudrKDtBdMJFAcxqrQdx27gosqPVyY3IvQ==";
      };
    };
    "deep-equal-0.1.2" = {
      name = "deep-equal";
      packageName = "deep-equal";
      version = "0.1.2";
      src = fetchurl {
        url = "https://registry.npmjs.org/deep-equal/-/deep-equal-0.1.2.tgz";
        sha512 = "rUCt39nKM7s6qUyYgp/reJmtXjgkOS/JbLO24DioMZaBNkD3b7C7cD3zJjSyjclEElNTpetAIRD6fMIbBIbX1Q==";
      };
    };
    "defined-0.0.0" = {
      name = "defined";
      packageName = "defined";
      version = "0.0.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/defined/-/defined-0.0.0.tgz";
        sha512 = "zpqiCT8bODLu3QSmLLic8xJnYWBFjOSu/fBCm189oAiTtPq/PSanNACKZDS7kgSyCJY7P+IcODzlIogBK/9RBg==";
      };
    };
    "deps-sort-0.1.2" = {
      name = "deps-sort";
      packageName = "deps-sort";
      version = "0.1.2";
      src = fetchurl {
        url = "https://registry.npmjs.org/deps-sort/-/deps-sort-0.1.2.tgz";
        sha512 = "bF5sJp2YeGQAx+vI3KBQwn6wHHyuCcsrPS0qvqnNLgGF1NrjhdvopP3exfdLLKaFtS6V5K/CMjQLtzR7C3Wa6A==";
      };
    };
    "detect-file-1.0.0" = {
      name = "detect-file";
      packageName = "detect-file";
      version = "1.0.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/detect-file/-/detect-file-1.0.0.tgz";
        sha512 = "DtCOLG98P007x7wiiOmfI0fi3eIKyWiLTGJ2MDnVi/E04lWGbf+JzrRHMm0rgIIZJGtHpKpbVgLWHrv8xXpc3Q==";
      };
    };
    "detective-2.1.2" = {
      name = "detective";
      packageName = "detective";
      version = "2.1.2";
      src = fetchurl {
        url = "https://registry.npmjs.org/detective/-/detective-2.1.2.tgz";
        sha512 = "hedmjOYPLbb9/WS8D8v1yRCMGnAvGBu8gQwyzODnpQ0PjvLybHpq4iiz3BQQ8UjvodC3r1qryOuo32PZgoSS8A==";
      };
    };
    "dom-serializer-0.2.2" = {
      name = "dom-serializer";
      packageName = "dom-serializer";
      version = "0.2.2";
      src = fetchurl {
        url = "https://registry.npmjs.org/dom-serializer/-/dom-serializer-0.2.2.tgz";
        sha512 = "2/xPb3ORsQ42nHYiSunXkDjPLBaEj/xTwUO4B7XCZQTRk7EBtTOPaygh10YAAh2OI1Qrp6NWfpAhzswj0ydt9g==";
      };
    };
    "domelementtype-1.3.1" = {
      name = "domelementtype";
      packageName = "domelementtype";
      version = "1.3.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/domelementtype/-/domelementtype-1.3.1.tgz";
        sha512 = "BSKB+TSpMpFI/HOxCNr1O8aMOTZ8hT3pM3GQ0w/mWRmkhEDSFJkkyzz4XQsBV44BChwGkrDfMyjVD0eA2aFV3w==";
      };
    };
    "domelementtype-2.3.0" = {
      name = "domelementtype";
      packageName = "domelementtype";
      version = "2.3.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/domelementtype/-/domelementtype-2.3.0.tgz";
        sha512 = "OLETBj6w0OsagBwdXnPdN0cnMfF9opN69co+7ZrbfPGrdpPVNBUj02spi6B1N7wChLQiPn4CSH/zJvXw56gmHw==";
      };
    };
    "domhandler-2.3.0" = {
      name = "domhandler";
      packageName = "domhandler";
      version = "2.3.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/domhandler/-/domhandler-2.3.0.tgz";
        sha512 = "q9bUwjfp7Eif8jWxxxPSykdRZAb6GkguBGSgvvCrhI9wB71W2K/Kvv4E61CF/mcCfnVJDeDWx/Vb/uAqbDj6UQ==";
      };
    };
    "domready-1.0.8" = {
      name = "domready";
      packageName = "domready";
      version = "1.0.8";
      src = fetchurl {
        url = "https://registry.npmjs.org/domready/-/domready-1.0.8.tgz";
        sha512 = "uIzsOJUNk+AdGE9a6VDeessoMCzF8RrZvJCX/W8QtyfgdR6Uofn/MvRonih3OtCO79b2VDzDOymuiABrQ4z3XA==";
      };
    };
    "domutils-1.5.1" = {
      name = "domutils";
      packageName = "domutils";
      version = "1.5.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/domutils/-/domutils-1.5.1.tgz";
        sha512 = "gSu5Oi/I+3wDENBsOWBiRK1eoGxcywYSqg3rR960/+EfY0CF4EX1VPkgHOZ3WiS/Jg2DtliF6BhWcHlfpYUcGw==";
      };
    };
    "duplexer-0.0.4" = {
      name = "duplexer";
      packageName = "duplexer";
      version = "0.0.4";
      src = fetchurl {
        url = "https://registry.npmjs.org/duplexer/-/duplexer-0.0.4.tgz";
        sha512 = "nO0WWuIDTde3CWK/8IPpG50dyhUilgpsqzYSIP+w20Yh+4iDgb/2Gs75QItcp0Hmx/JtxtTXBalj+LSTD1VemA==";
      };
    };
    "duplexer-0.1.2" = {
      name = "duplexer";
      packageName = "duplexer";
      version = "0.1.2";
      src = fetchurl {
        url = "https://registry.npmjs.org/duplexer/-/duplexer-0.1.2.tgz";
        sha512 = "jtD6YG370ZCIi/9GTaJKQxWTZD045+4R4hTk/x1UyoqadyJ9x9CgSi1RlVDQF8U2sxLLSnFkCaMihqljHIWgMg==";
      };
    };
    "entities-1.0.0" = {
      name = "entities";
      packageName = "entities";
      version = "1.0.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/entities/-/entities-1.0.0.tgz";
        sha512 = "LbLqfXgJMmy81t+7c14mnulFHJ170cM6E+0vMXR9k/ZiZwgX8i5pNgjTCX3SO4VeUsFLV+8InixoretwU+MjBQ==";
      };
    };
    "entities-2.2.0" = {
      name = "entities";
      packageName = "entities";
      version = "2.2.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/entities/-/entities-2.2.0.tgz";
        sha512 = "p92if5Nz619I0w+akJrLZH0MX0Pb5DX39XOwQTtXSdQQOaYH03S1uIQp4mhOZtAXrxq4ViO67YTiLBo2638o9A==";
      };
    };
    "errno-0.1.8" = {
      name = "errno";
      packageName = "errno";
      version = "0.1.8";
      src = fetchurl {
        url = "https://registry.npmjs.org/errno/-/errno-0.1.8.tgz";
        sha512 = "dJ6oBr5SQ1VSd9qkk7ByRgb/1SH4JZjCHSW/mr63/QcXO9zLVxvJ6Oy13nio03rxpSnVDDjFor75SjVeZWPW/A==";
      };
    };
    "error-7.2.1" = {
      name = "error";
      packageName = "error";
      version = "7.2.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/error/-/error-7.2.1.tgz";
        sha512 = "fo9HBvWnx3NGUKMvMwB/CBCMMrfEJgbDTVDEkPygA3Bdd3lM1OyCd+rbQ8BwnpF6GdVeOLDNmyL4N5Bg80ZvdA==";
      };
    };
    "escodegen-0.0.15" = {
      name = "escodegen";
      packageName = "escodegen";
      version = "0.0.15";
      src = fetchurl {
        url = "https://registry.npmjs.org/escodegen/-/escodegen-0.0.15.tgz";
        sha512 = "ALdTVKqhEj6bDf4pC0fXWRiUvhyJSJ0Ic8AdPuMGKckoa3gMXG+MPduI8TlDoSS84swDkfXeogXapbkErAHvDA==";
      };
    };
    "esprima-0.9.9" = {
      name = "esprima";
      packageName = "esprima";
      version = "0.9.9";
      src = fetchurl {
        url = "https://registry.npmjs.org/esprima/-/esprima-0.9.9.tgz";
        sha512 = "uTFHqyoMus4csxVp8FSqPajg59VwNt0PshVERqiIjPed6L9IG0pYz/zbhZ2HFFvn8AKzduipZP6mFxr3dr18ag==";
      };
    };
    "esprima-1.0.2" = {
      name = "esprima";
      packageName = "esprima";
      version = "1.0.2";
      src = fetchurl {
        url = "https://registry.npmjs.org/esprima/-/esprima-1.0.2.tgz";
        sha512 = "j2ZAN1Cm/rgsIEHgNa6eqvZjEtqFh8WEUdVswEpxj03AyzR1R6CHfunOpd9NOmLg0U18aAO2FunAjs49f5w0Yg==";
      };
    };
    "esprima-4.0.1" = {
      name = "esprima";
      packageName = "esprima";
      version = "4.0.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/esprima/-/esprima-4.0.1.tgz";
        sha512 = "eGuFFw7Upda+g4p+QHvnW0RyTX/SVeJBDM/gCtMARO0cLuT2HcEKnTPvhjV6aGeqrCB/sbNop0Kszm0jsaWU4A==";
      };
    };
    "eventemitter2-0.4.14" = {
      name = "eventemitter2";
      packageName = "eventemitter2";
      version = "0.4.14";
      src = fetchurl {
        url = "https://registry.npmjs.org/eventemitter2/-/eventemitter2-0.4.14.tgz";
        sha512 = "K7J4xq5xAD5jHsGM5ReWXRTFa3JRGofHiMcVgQ8PRwgWxzjHpMWCIzsmyf60+mh8KLsqYPcjUMa0AC4hd6lPyQ==";
      };
    };
    "exit-0.1.2" = {
      name = "exit";
      packageName = "exit";
      version = "0.1.2";
      src = fetchurl {
        url = "https://registry.npmjs.org/exit/-/exit-0.1.2.tgz";
        sha512 = "Zk/eNKV2zbjpKzrsQ+n1G6poVbErQxJ0LBOJXaKZ1EViLzH+hrLu9cdXI4zw9dBQJslwBEpbQ2P1oS7nDxs6jQ==";
      };
    };
    "expand-tilde-2.0.2" = {
      name = "expand-tilde";
      packageName = "expand-tilde";
      version = "2.0.2";
      src = fetchurl {
        url = "https://registry.npmjs.org/expand-tilde/-/expand-tilde-2.0.2.tgz";
        sha512 = "A5EmesHW6rfnZ9ysHQjPdJRni0SRar0tjtG5MNtm9n5TUvsYU8oozprtRD4AqHxcZWWlVuAmQo2nWKfN9oyjTw==";
      };
    };
    "extend-3.0.2" = {
      name = "extend";
      packageName = "extend";
      version = "3.0.2";
      src = fetchurl {
        url = "https://registry.npmjs.org/extend/-/extend-3.0.2.tgz";
        sha512 = "fjquC59cD7CyW6urNXK0FBufkZcoiGG80wTuPujX590cB5Ttln20E2UB4S/WARVqhXffZl2LNgS+gQdPIIim/g==";
      };
    };
    "faye-websocket-0.10.0" = {
      name = "faye-websocket";
      packageName = "faye-websocket";
      version = "0.10.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/faye-websocket/-/faye-websocket-0.10.0.tgz";
        sha512 = "Xhj93RXbMSq8urNCUq4p9l0P6hnySJ/7YNRhYNug0bLOuii7pKO7xQFb5mx9xZXWCar88pLPb805PvUkwrLZpQ==";
      };
    };
    "fill-range-7.0.1" = {
      name = "fill-range";
      packageName = "fill-range";
      version = "7.0.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/fill-range/-/fill-range-7.0.1.tgz";
        sha512 = "qOo9F+dMUmC2Lcb4BbVvnKJxTPjCm+RRpe4gDuGrzkL7mEVl/djYSu2OdQ2Pa302N4oqkSg9ir6jaLWJ2USVpQ==";
      };
    };
    "findup-sync-0.3.0" = {
      name = "findup-sync";
      packageName = "findup-sync";
      version = "0.3.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/findup-sync/-/findup-sync-0.3.0.tgz";
        sha512 = "z8Nrwhi6wzxNMIbxlrTzuUW6KWuKkogZ/7OdDVq+0+kxn77KUH1nipx8iU6suqkHqc4y6n7a9A8IpmxY/pTjWg==";
      };
    };
    "findup-sync-4.0.0" = {
      name = "findup-sync";
      packageName = "findup-sync";
      version = "4.0.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/findup-sync/-/findup-sync-4.0.0.tgz";
        sha512 = "6jvvn/12IC4quLBL1KNokxC7wWTvYncaVUYSoxWw7YykPLuRrnv4qdHcSOywOI5RpkOVGeQRtWM8/q+G6W6qfQ==";
      };
    };
    "fined-1.2.0" = {
      name = "fined";
      packageName = "fined";
      version = "1.2.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/fined/-/fined-1.2.0.tgz";
        sha512 = "ZYDqPLGxDkDhDZBjZBb+oD1+j0rA4E0pXY50eplAAOPg2N/gUBSSk5IM1/QhPfyVo19lJ+CvXpqfvk+b2p/8Ng==";
      };
    };
    "flagged-respawn-1.0.1" = {
      name = "flagged-respawn";
      packageName = "flagged-respawn";
      version = "1.0.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/flagged-respawn/-/flagged-respawn-1.0.1.tgz";
        sha512 = "lNaHNVymajmk0OJMBn8fVUAU1BtDeKIqKoVhk4xAALB57aALg6b4W0MfJ/cUE0g9YBXy5XhSlPIpYIJ7HaY/3Q==";
      };
    };
    "for-in-1.0.2" = {
      name = "for-in";
      packageName = "for-in";
      version = "1.0.2";
      src = fetchurl {
        url = "https://registry.npmjs.org/for-in/-/for-in-1.0.2.tgz";
        sha512 = "7EwmXrOjyL+ChxMhmG5lnW9MPt1aIeZEwKhQzoBUdTV0N3zuwWDZYVJatDvZ2OyzPUvdIAZDsCetk3coyMfcnQ==";
      };
    };
    "for-own-1.0.0" = {
      name = "for-own";
      packageName = "for-own";
      version = "1.0.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/for-own/-/for-own-1.0.0.tgz";
        sha512 = "0OABksIGrxKK8K4kynWkQ7y1zounQxP+CWnyclVwj81KW3vlLlGUx57DKGcP/LH216GzqnstnPocF16Nxs0Ycg==";
      };
    };
    "fs.realpath-1.0.0" = {
      name = "fs.realpath";
      packageName = "fs.realpath";
      version = "1.0.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/fs.realpath/-/fs.realpath-1.0.0.tgz";
        sha512 = "OO0pH2lK6a0hZnAdau5ItzHPI6pUlvI7jMVnxUQRtw4owF2wk8lOSabtGDCTP4Ggrg2MbGnWO9X8K1t4+fGMDw==";
      };
    };
    "function-bind-1.1.1" = {
      name = "function-bind";
      packageName = "function-bind";
      version = "1.1.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/function-bind/-/function-bind-1.1.1.tgz";
        sha512 = "yIovAzMX49sF8Yl58fSCWJ5svSLuaibPxXQJFLmBObTuCr0Mf1KiPopGM9NiFjiYBCbfaa2Fh6breQ6ANVTI0A==";
      };
    };
    "gaze-1.1.3" = {
      name = "gaze";
      packageName = "gaze";
      version = "1.1.3";
      src = fetchurl {
        url = "https://registry.npmjs.org/gaze/-/gaze-1.1.3.tgz";
        sha512 = "BRdNm8hbWzFzWHERTrejLqwHDfS4GibPoq5wjTPIoJHoBtKGPg3xAFfxmM+9ztbXelxcf2hwQcaz1PtmFeue8g==";
      };
    };
    "get-intrinsic-1.1.3" = {
      name = "get-intrinsic";
      packageName = "get-intrinsic";
      version = "1.1.3";
      src = fetchurl {
        url = "https://registry.npmjs.org/get-intrinsic/-/get-intrinsic-1.1.3.tgz";
        sha512 = "QJVz1Tj7MS099PevUG5jvnt9tSkXN8K14dxQlikJuPt4uD9hHAHjLyLBiLR5zELelBdD9QNRAXZzsJx0WaDL9A==";
      };
    };
    "getobject-1.0.2" = {
      name = "getobject";
      packageName = "getobject";
      version = "1.0.2";
      src = fetchurl {
        url = "https://registry.npmjs.org/getobject/-/getobject-1.0.2.tgz";
        sha512 = "2zblDBaFcb3rB4rF77XVnuINOE2h2k/OnqXAiy0IrTxUfV1iFp3la33oAQVY9pCpWU268WFYVt2t71hlMuLsOg==";
      };
    };
    "glob-5.0.15" = {
      name = "glob";
      packageName = "glob";
      version = "5.0.15";
      src = fetchurl {
        url = "https://registry.npmjs.org/glob/-/glob-5.0.15.tgz";
        sha512 = "c9IPMazfRITpmAAKi22dK1VKxGDX9ehhqfABDriL/lzO92xcUKEJPQHrVA/2YHSNFB4iFlykVmWvwo48nr3OxA==";
      };
    };
    "glob-7.1.7" = {
      name = "glob";
      packageName = "glob";
      version = "7.1.7";
      src = fetchurl {
        url = "https://registry.npmjs.org/glob/-/glob-7.1.7.tgz";
        sha512 = "OvD9ENzPLbegENnYP5UUfJIirTg4+XwMWGaQfQTY0JenxNvvIKP3U3/tAQSPIu/lHxXYSZmpXlUHeqAIdKzBLQ==";
      };
    };
    "global-modules-1.0.0" = {
      name = "global-modules";
      packageName = "global-modules";
      version = "1.0.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/global-modules/-/global-modules-1.0.0.tgz";
        sha512 = "sKzpEkf11GpOFuw0Zzjzmt4B4UZwjOcG757PPvrfhxcLFbq0wpsgpOqxpxtxFiCG4DtG93M6XRVbF2oGdev7bg==";
      };
    };
    "global-prefix-1.0.2" = {
      name = "global-prefix";
      packageName = "global-prefix";
      version = "1.0.2";
      src = fetchurl {
        url = "https://registry.npmjs.org/global-prefix/-/global-prefix-1.0.2.tgz";
        sha512 = "5lsx1NUDHtSjfg0eHlmYvZKv8/nVqX4ckFbM+FrGcQ+04KWcWFo9P5MxPZYSzUvyzmdTbI7Eix8Q4IbELDqzKg==";
      };
    };
    "globule-1.3.4" = {
      name = "globule";
      packageName = "globule";
      version = "1.3.4";
      src = fetchurl {
        url = "https://registry.npmjs.org/globule/-/globule-1.3.4.tgz";
        sha512 = "OPTIfhMBh7JbBYDpa5b+Q5ptmMWKwcNcFSR/0c6t8V4f3ZAVBEsKNY37QdVqmLRYSMhOUGYrY0QhSoEpzGr/Eg==";
      };
    };
    "glur-1.1.2" = {
      name = "glur";
      packageName = "glur";
      version = "1.1.2";
      src = fetchurl {
        url = "https://registry.npmjs.org/glur/-/glur-1.1.2.tgz";
        sha512 = "l+8esYHTKOx2G/Aao4lEQ0bnHWg4fWtJbVoZZT9Knxi01pB8C80BR85nONLFwkkQoFRCmXY+BUcGZN3yZ2QsRA==";
      };
    };
    "graceful-fs-4.2.10" = {
      name = "graceful-fs";
      packageName = "graceful-fs";
      version = "4.2.10";
      src = fetchurl {
        url = "https://registry.npmjs.org/graceful-fs/-/graceful-fs-4.2.10.tgz";
        sha512 = "9ByhssR2fPVsNZj478qUUbKfmL0+t5BDVyjShtyZZLiK7ZDAArFFfopyOTj0M05wE2tJPisA4iTnnXl2YoPvOA==";
      };
    };
    "grunt-1.5.3" = {
      name = "grunt";
      packageName = "grunt";
      version = "1.5.3";
      src = fetchurl {
        url = "https://registry.npmjs.org/grunt/-/grunt-1.5.3.tgz";
        sha512 = "mKwmo4X2d8/4c/BmcOETHek675uOqw0RuA/zy12jaspWqvTp4+ZeQF1W+OTpcbncnaBsfbQJ6l0l4j+Sn/GmaQ==";
      };
    };
    "grunt-asset-cachebuster-0.5.0" = {
      name = "grunt-asset-cachebuster";
      packageName = "grunt-asset-cachebuster";
      version = "0.5.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/grunt-asset-cachebuster/-/grunt-asset-cachebuster-0.5.0.tgz";
        sha512 = "vSd9pq1XrDoQrFfCWr8drVRtX6AbSWxfJKJ8j/5UMBJp9ZAwNIgn1rkqMwIWl3x1lIdYdKmWcoZ4Kkui9iQMyg==";
      };
    };
    "grunt-cli-1.4.3" = {
      name = "grunt-cli";
      packageName = "grunt-cli";
      version = "1.4.3";
      src = fetchurl {
        url = "https://registry.npmjs.org/grunt-cli/-/grunt-cli-1.4.3.tgz";
        sha512 = "9Dtx/AhVeB4LYzsViCjUQkd0Kw0McN2gYpdmGYKtE2a5Yt7v1Q+HYZVWhqXc/kGnxlMtqKDxSwotiGeFmkrCoQ==";
      };
    };
    "grunt-contrib-jshint-3.2.0" = {
      name = "grunt-contrib-jshint";
      packageName = "grunt-contrib-jshint";
      version = "3.2.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/grunt-contrib-jshint/-/grunt-contrib-jshint-3.2.0.tgz";
        sha512 = "pcXWCSZWfoMSvcV4BwH21TUtLtcX0Ms8IGuOPIcLeXK3fud9KclY7iqMKY94jFx8TxZzh028YYtpR+io8DiEaQ==";
      };
    };
    "grunt-contrib-less-3.0.0" = {
      name = "grunt-contrib-less";
      packageName = "grunt-contrib-less";
      version = "3.0.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/grunt-contrib-less/-/grunt-contrib-less-3.0.0.tgz";
        sha512 = "fBB8MUDCo5EgT7WdOVQnZq4GF+XCeFdnkhaxI7uepp8P973sH1jdodjF87c6d9WSHKgArJAGP5JEtthhdKVovg==";
      };
    };
    "grunt-contrib-watch-1.1.0" = {
      name = "grunt-contrib-watch";
      packageName = "grunt-contrib-watch";
      version = "1.1.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/grunt-contrib-watch/-/grunt-contrib-watch-1.1.0.tgz";
        sha512 = "yGweN+0DW5yM+oo58fRu/XIRrPcn3r4tQx+nL7eMRwjpvk+rQY6R8o94BPK0i2UhTg9FN21hS+m8vR8v9vXfeg==";
      };
    };
    "grunt-known-options-2.0.0" = {
      name = "grunt-known-options";
      packageName = "grunt-known-options";
      version = "2.0.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/grunt-known-options/-/grunt-known-options-2.0.0.tgz";
        sha512 = "GD7cTz0I4SAede1/+pAbmJRG44zFLPipVtdL9o3vqx9IEyb7b4/Y3s7r6ofI3CchR5GvYJ+8buCSioDv5dQLiA==";
      };
    };
    "grunt-legacy-log-3.0.0" = {
      name = "grunt-legacy-log";
      packageName = "grunt-legacy-log";
      version = "3.0.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/grunt-legacy-log/-/grunt-legacy-log-3.0.0.tgz";
        sha512 = "GHZQzZmhyq0u3hr7aHW4qUH0xDzwp2YXldLPZTCjlOeGscAOWWPftZG3XioW8MasGp+OBRIu39LFx14SLjXRcA==";
      };
    };
    "grunt-legacy-log-utils-2.1.0" = {
      name = "grunt-legacy-log-utils";
      packageName = "grunt-legacy-log-utils";
      version = "2.1.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/grunt-legacy-log-utils/-/grunt-legacy-log-utils-2.1.0.tgz";
        sha512 = "lwquaPXJtKQk0rUM1IQAop5noEpwFqOXasVoedLeNzaibf/OPWjKYvvdqnEHNmU+0T0CaReAXIbGo747ZD+Aaw==";
      };
    };
    "grunt-legacy-util-2.0.1" = {
      name = "grunt-legacy-util";
      packageName = "grunt-legacy-util";
      version = "2.0.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/grunt-legacy-util/-/grunt-legacy-util-2.0.1.tgz";
        sha512 = "2bQiD4fzXqX8rhNdXkAywCadeqiPiay0oQny77wA2F3WF4grPJXCvAcyoWUJV+po/b15glGkxuSiQCK299UC2w==";
      };
    };
    "grunt-watchify-0.1.0" = {
      name = "grunt-watchify";
      packageName = "grunt-watchify";
      version = "0.1.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/grunt-watchify/-/grunt-watchify-0.1.0.tgz";
        sha512 = "xlsvjN1Dj098oImgWq3Tkdw6WgjuSSs8ZrzYEbhvBxip/SOCc5NKn/HMJFYHJgPfKRnGnkADgJCmT068NM93EA==";
      };
    };
    "has-1.0.3" = {
      name = "has";
      packageName = "has";
      version = "1.0.3";
      src = fetchurl {
        url = "https://registry.npmjs.org/has/-/has-1.0.3.tgz";
        sha512 = "f2dvO0VU6Oej7RkWJGrehjbzMAjFp5/VKPp5tTpWIV4JHHZK1/BxbFRtf/siA2SWTe09caDmVtYYzWEIbBS4zw==";
      };
    };
    "has-flag-4.0.0" = {
      name = "has-flag";
      packageName = "has-flag";
      version = "4.0.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/has-flag/-/has-flag-4.0.0.tgz";
        sha512 = "EykJT/Q1KjTWctppgIAgfSO0tKVuZUjhgMr17kqTumMl6Afv3EISleU7qZUzoXDFTAHTDC4NOoG/ZxU3EvlMPQ==";
      };
    };
    "has-symbols-1.0.3" = {
      name = "has-symbols";
      packageName = "has-symbols";
      version = "1.0.3";
      src = fetchurl {
        url = "https://registry.npmjs.org/has-symbols/-/has-symbols-1.0.3.tgz";
        sha512 = "l3LCuF6MgDNwTDKkdYGEihYjt5pRPbEg46rtlmnSPlUbgmB8LOIrKJbYYFBSbnPaJexMKtiPO8hmeRjRz2Td+A==";
      };
    };
    "homedir-polyfill-1.0.3" = {
      name = "homedir-polyfill";
      packageName = "homedir-polyfill";
      version = "1.0.3";
      src = fetchurl {
        url = "https://registry.npmjs.org/homedir-polyfill/-/homedir-polyfill-1.0.3.tgz";
        sha512 = "eSmmWE5bZTK2Nou4g0AI3zZ9rswp7GRKoKXS1BLUkvPviOqs4YTN1djQIqrXy9k5gEtdLPy86JjRwsNM9tnDcA==";
      };
    };
    "hooker-0.2.3" = {
      name = "hooker";
      packageName = "hooker";
      version = "0.2.3";
      src = fetchurl {
        url = "https://registry.npmjs.org/hooker/-/hooker-0.2.3.tgz";
        sha512 = "t+UerCsQviSymAInD01Pw+Dn/usmz1sRO+3Zk1+lx8eg+WKpD2ulcwWqHHL0+aseRBr+3+vIhiG1K1JTwaIcTA==";
      };
    };
    "htmlparser2-3.8.3" = {
      name = "htmlparser2";
      packageName = "htmlparser2";
      version = "3.8.3";
      src = fetchurl {
        url = "https://registry.npmjs.org/htmlparser2/-/htmlparser2-3.8.3.tgz";
        sha512 = "hBxEg3CYXe+rPIua8ETe7tmG3XDn9B0edOE/e9wH2nLczxzgdu0m0aNHY+5wFZiviLWLdANPJTssa92dMcXQ5Q==";
      };
    };
    "http-browserify-0.1.14" = {
      name = "http-browserify";
      packageName = "http-browserify";
      version = "0.1.14";
      src = fetchurl {
        url = "https://registry.npmjs.org/http-browserify/-/http-browserify-0.1.14.tgz";
        sha512 = "q9Gd3S/dVbLBhRsEQh3R7/Y1aHUvdqdfgHWt/QQRwInX5Cji6bCQhD5yXbcV2c03bApRdYpTDQ0XZSIR2o7nWg==";
      };
    };
    "http-parser-js-0.5.8" = {
      name = "http-parser-js";
      packageName = "http-parser-js";
      version = "0.5.8";
      src = fetchurl {
        url = "https://registry.npmjs.org/http-parser-js/-/http-parser-js-0.5.8.tgz";
        sha512 = "SGeBX54F94Wgu5RH3X5jsDtf4eHyRogWX1XGT3b4HuW3tQPM4AaBzoUji/4AAJNXCEOWZ5O0DgZmJw1947gD5Q==";
      };
    };
    "iconv-lite-0.4.24" = {
      name = "iconv-lite";
      packageName = "iconv-lite";
      version = "0.4.24";
      src = fetchurl {
        url = "https://registry.npmjs.org/iconv-lite/-/iconv-lite-0.4.24.tgz";
        sha512 = "v3MXnZAcvnywkTUEZomIActle7RXXeedOR31wwl7VlyoXO4Qi9arvSenNQWne1TcRwhCL1HwLI21bEqdpj8/rA==";
      };
    };
    "iconv-lite-0.6.3" = {
      name = "iconv-lite";
      packageName = "iconv-lite";
      version = "0.6.3";
      src = fetchurl {
        url = "https://registry.npmjs.org/iconv-lite/-/iconv-lite-0.6.3.tgz";
        sha512 = "4fCk79wshMdzMp2rH06qWrJE4iolqLhCUH+OiuIgU++RB0+94NlDL81atO7GX55uUKueo0txHNtvEyI6D7WdMw==";
      };
    };
    "image-size-0.5.5" = {
      name = "image-size";
      packageName = "image-size";
      version = "0.5.5";
      src = fetchurl {
        url = "https://registry.npmjs.org/image-size/-/image-size-0.5.5.tgz";
        sha512 = "6TDAlDPZxUFCv+fuOkIoXT/V/f3Qbq8e37p+YOiYrUv3v9cc3/6x78VdfPgFVaB9dZYeLUfKgHRebpkm/oP2VQ==";
      };
    };
    "indexof-0.0.1" = {
      name = "indexof";
      packageName = "indexof";
      version = "0.0.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/indexof/-/indexof-0.0.1.tgz";
        sha512 = "i0G7hLJ1z0DE8dsqJa2rycj9dBmNKgXBvotXtZYXakU9oivfB9Uj2ZBC27qqef2U58/ZLwalxa1X/RDCdkHtVg==";
      };
    };
    "inflight-1.0.6" = {
      name = "inflight";
      packageName = "inflight";
      version = "1.0.6";
      src = fetchurl {
        url = "https://registry.npmjs.org/inflight/-/inflight-1.0.6.tgz";
        sha512 = "k92I/b08q4wvFscXCLvqfsHCrjrF7yiXsQuIVvVE7N82W3+aqpzuUdBbfhWcy/FZR3/4IgflMgKLOsvPDrGCJA==";
      };
    };
    "inherits-1.0.2" = {
      name = "inherits";
      packageName = "inherits";
      version = "1.0.2";
      src = fetchurl {
        url = "https://registry.npmjs.org/inherits/-/inherits-1.0.2.tgz";
        sha512 = "Al67oatbRSo3RV5hRqIoln6Y5yMVbJSIn4jEJNL7VCImzq/kLr7vvb6sFRJXqr8rpHc/2kJOM+y0sPKN47VdzA==";
      };
    };
    "inherits-2.0.4" = {
      name = "inherits";
      packageName = "inherits";
      version = "2.0.4";
      src = fetchurl {
        url = "https://registry.npmjs.org/inherits/-/inherits-2.0.4.tgz";
        sha512 = "k/vGaX4/Yla3WzyMCvTQOXYeIHvqOKtnqBduzTHpzpQZzAskKMhZ2K+EnBiSM9zGSoIFeMpXKxa4dYeZIQqewQ==";
      };
    };
    "ini-1.3.8" = {
      name = "ini";
      packageName = "ini";
      version = "1.3.8";
      src = fetchurl {
        url = "https://registry.npmjs.org/ini/-/ini-1.3.8.tgz";
        sha512 = "JV/yugV2uzW5iMRSiZAyDtQd+nxtUnjeLt0acNdw98kKLrvuRVyB80tsREOE7yvGVgalhZ6RNXCmEHkUKBKxew==";
      };
    };
    "inline-source-map-0.3.1" = {
      name = "inline-source-map";
      packageName = "inline-source-map";
      version = "0.3.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/inline-source-map/-/inline-source-map-0.3.1.tgz";
        sha512 = "RNlldBXZ7BBcVm3HjXIXiwKxih1lnuKbzeLBRDSB/qaqk8/g4JEZBjxpBQMhqEthQyGv7ycu8r/8PKGgBdIqrA==";
      };
    };
    "insert-module-globals-1.3.1" = {
      name = "insert-module-globals";
      packageName = "insert-module-globals";
      version = "1.3.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/insert-module-globals/-/insert-module-globals-1.3.1.tgz";
        sha512 = "ZqHb9aHVV7KG+xMOKeBcQ/AOQKtMFVOUOZXNJG7ZXtglblbH0Q5b7o+dsVMNgifTuf+H5noiUVFsSM1v+Pw//g==";
      };
    };
    "interpolate-0.1.0" = {
      name = "interpolate";
      packageName = "interpolate";
      version = "0.1.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/interpolate/-/interpolate-0.1.0.tgz";
        sha512 = "IHNHKuwhIPaSHjhmEgCzMko+pzpn+G+qXDViwnqx3L0E7Y5DeoMsKH7WfNpDJTiZrbGirsMeaJRbzTI56le7Jg==";
      };
    };
    "interpret-1.1.0" = {
      name = "interpret";
      packageName = "interpret";
      version = "1.1.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/interpret/-/interpret-1.1.0.tgz";
        sha512 = "CLM8SNMDu7C5psFCn6Wg/tgpj/bKAg7hc2gWqcuR9OD5Ft9PhBpIu8PLicPeis+xDd6YX2ncI8MCA64I9tftIA==";
      };
    };
    "is-absolute-1.0.0" = {
      name = "is-absolute";
      packageName = "is-absolute";
      version = "1.0.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/is-absolute/-/is-absolute-1.0.0.tgz";
        sha512 = "dOWoqflvcydARa360Gvv18DZ/gRuHKi2NU/wU5X1ZFzdYfH29nkiNZsF3mp4OJ3H4yo9Mx8A/uAGNzpzPN3yBA==";
      };
    };
    "is-core-module-2.11.0" = {
      name = "is-core-module";
      packageName = "is-core-module";
      version = "2.11.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/is-core-module/-/is-core-module-2.11.0.tgz";
        sha512 = "RRjxlvLDkD1YJwDbroBHMb+cukurkDWNyHx7D3oNB5x9rb5ogcksMC5wHCadcXoo67gVr/+3GFySh3134zi6rw==";
      };
    };
    "is-extglob-2.1.1" = {
      name = "is-extglob";
      packageName = "is-extglob";
      version = "2.1.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/is-extglob/-/is-extglob-2.1.1.tgz";
        sha512 = "SbKbANkN603Vi4jEZv49LeVJMn4yGwsbzZworEoyEiutsN3nJYdbO36zfhGJ6QEDpOZIFkDtnq5JRxmvl3jsoQ==";
      };
    };
    "is-glob-4.0.3" = {
      name = "is-glob";
      packageName = "is-glob";
      version = "4.0.3";
      src = fetchurl {
        url = "https://registry.npmjs.org/is-glob/-/is-glob-4.0.3.tgz";
        sha512 = "xelSayHH36ZgE7ZWhli7pW34hNbNl8Ojv5KVmkJD4hBdD3th8Tfk9vYasLM+mXWOZhFkgZfxhLSnrwRr4elSSg==";
      };
    };
    "is-number-7.0.0" = {
      name = "is-number";
      packageName = "is-number";
      version = "7.0.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/is-number/-/is-number-7.0.0.tgz";
        sha512 = "41Cifkg6e8TylSpdtTpeLVMqvSBEVzTttHvERD741+pnZ8ANv0004MRL43QKPDlK9cGvNp6NZWZUBlbGXYxxng==";
      };
    };
    "is-plain-object-2.0.4" = {
      name = "is-plain-object";
      packageName = "is-plain-object";
      version = "2.0.4";
      src = fetchurl {
        url = "https://registry.npmjs.org/is-plain-object/-/is-plain-object-2.0.4.tgz";
        sha512 = "h5PpgXkWitc38BBMYawTYMWJHFZJVnBquFE57xFpjB8pJFiF6gZ+bU+WyI/yqXiFR5mdLsgYNaPe8uao6Uv9Og==";
      };
    };
    "is-relative-1.0.0" = {
      name = "is-relative";
      packageName = "is-relative";
      version = "1.0.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/is-relative/-/is-relative-1.0.0.tgz";
        sha512 = "Kw/ReK0iqwKeu0MITLFuj0jbPAmEiOsIwyIXvvbfa6QfmN9pkD1M+8pdk7Rl/dTKbH34/XBFMbgD4iMJhLQbGA==";
      };
    };
    "is-unc-path-1.0.0" = {
      name = "is-unc-path";
      packageName = "is-unc-path";
      version = "1.0.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/is-unc-path/-/is-unc-path-1.0.0.tgz";
        sha512 = "mrGpVd0fs7WWLfVsStvgF6iEJnbjDFZh9/emhRDcGWTduTfNHd9CHeUwH3gYIjdbwo4On6hunkztwOaAw0yllQ==";
      };
    };
    "is-what-3.14.1" = {
      name = "is-what";
      packageName = "is-what";
      version = "3.14.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/is-what/-/is-what-3.14.1.tgz";
        sha512 = "sNxgpk9793nzSs7bA6JQJGeIuRBQhAaNGG77kzYQgMkrID+lS6SlK07K5LaptscDlSaIgH+GPFzf+d75FVxozA==";
      };
    };
    "is-windows-1.0.2" = {
      name = "is-windows";
      packageName = "is-windows";
      version = "1.0.2";
      src = fetchurl {
        url = "https://registry.npmjs.org/is-windows/-/is-windows-1.0.2.tgz";
        sha512 = "eXK1UInq2bPmjyX6e3VHIzMLobc4J94i4AWn+Hpq3OU5KkrRC96OAcR3PRJ/pGu6m8TRnBHP9dkXQVsT/COVIA==";
      };
    };
    "isarray-0.0.1" = {
      name = "isarray";
      packageName = "isarray";
      version = "0.0.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/isarray/-/isarray-0.0.1.tgz";
        sha512 = "D2S+3GLxWH+uhrNEcoh/fnmYeP8E8/zHl644d/jdA0g2uyXvy3sb0qxotE+ne0LtccHknQzWwZEzhak7oJ0COQ==";
      };
    };
    "isexe-2.0.0" = {
      name = "isexe";
      packageName = "isexe";
      version = "2.0.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/isexe/-/isexe-2.0.0.tgz";
        sha512 = "RHxMLp9lnKHGHRng9QFhRCMbYAcVpn69smSGcq3f36xjgVVWThj4qqLbTLlq7Ssj8B+fIQ1EuCEGI2lKsyQeIw==";
      };
    };
    "isobject-3.0.1" = {
      name = "isobject";
      packageName = "isobject";
      version = "3.0.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/isobject/-/isobject-3.0.1.tgz";
        sha512 = "WhB9zCku7EGTj/HQQRz5aUQEUeoQZH2bWcltRErOpymJ4boYE6wL9Tbr23krRPSZ+C5zqNSrSw+Cc7sZZ4b7vg==";
      };
    };
    "js-yaml-3.14.1" = {
      name = "js-yaml";
      packageName = "js-yaml";
      version = "3.14.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/js-yaml/-/js-yaml-3.14.1.tgz";
        sha512 = "okMH7OXXJ7YrN9Ok3/SXrnu4iX9yOk+25nqX4imS2npuvTYDmo/QEZoqwZkYaIDk3jVvBOTOIEgEhaLOynBS9g==";
      };
    };
    "jshint-2.13.6" = {
      name = "jshint";
      packageName = "jshint";
      version = "2.13.6";
      src = fetchurl {
        url = "https://registry.npmjs.org/jshint/-/jshint-2.13.6.tgz";
        sha512 = "IVdB4G0NTTeQZrBoM8C5JFVLjV2KtZ9APgybDA1MK73xb09qFs0jCXyQLnCOp1cSZZZbvhq/6mfXHUTaDkffuQ==";
      };
    };
    "jsonify-0.0.1" = {
      name = "jsonify";
      packageName = "jsonify";
      version = "0.0.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/jsonify/-/jsonify-0.0.1.tgz";
        sha512 = "2/Ki0GcmuqSrgFyelQq9M05y7PS0mEwuIzrf3f1fPqkVDVRvZrPZtVSMHxdgo8Aq0sxAOb/cr2aqqA3LeWHVPg==";
      };
    };
    "jsonparse-0.0.5" = {
      name = "jsonparse";
      packageName = "jsonparse";
      version = "0.0.5";
      src = fetchurl {
        url = "https://registry.npmjs.org/jsonparse/-/jsonparse-0.0.5.tgz";
        sha512 = "fw7Q/8gFR8iSekUi9I+HqWIap6mywuoe7hQIg3buTVjuZgALKj4HAmm0X6f+TaL4c9NJbvyFQdaI2ppr5p6dnQ==";
      };
    };
    "kind-of-6.0.3" = {
      name = "kind-of";
      packageName = "kind-of";
      version = "6.0.3";
      src = fetchurl {
        url = "https://registry.npmjs.org/kind-of/-/kind-of-6.0.3.tgz";
        sha512 = "dcS1ul+9tmeD95T+x28/ehLgd9mENa3LsvDTtzm3vyBEO7RPptvAD+t44WVXaUjTBRcrpFeFlC8WCruUR456hw==";
      };
    };
    "less-4.1.3" = {
      name = "less";
      packageName = "less";
      version = "4.1.3";
      src = fetchurl {
        url = "https://registry.npmjs.org/less/-/less-4.1.3.tgz";
        sha512 = "w16Xk/Ta9Hhyei0Gpz9m7VS8F28nieJaL/VyShID7cYvP6IL5oHeL6p4TXSDJqZE/lNv0oJ2pGVjJsRkfwm5FA==";
      };
    };
    "lexical-scope-0.0.15" = {
      name = "lexical-scope";
      packageName = "lexical-scope";
      version = "0.0.15";
      src = fetchurl {
        url = "https://registry.npmjs.org/lexical-scope/-/lexical-scope-0.0.15.tgz";
        sha512 = "w2GlDzW3WYJcytiVfNeFKYQ4CUZJDBP8vtxkqD3jCjgqei4IbvMJu8EMhNXHbH//yW2hTVz04/Zbhi7eNeGEaw==";
      };
    };
    "liftup-3.0.1" = {
      name = "liftup";
      packageName = "liftup";
      version = "3.0.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/liftup/-/liftup-3.0.1.tgz";
        sha512 = "yRHaiQDizWSzoXk3APcA71eOI/UuhEkNN9DiW2Tt44mhYzX4joFoCZlxsSOF7RyeLlfqzFLQI1ngFq3ggMPhOw==";
      };
    };
    "livereload-js-2.4.0" = {
      name = "livereload-js";
      packageName = "livereload-js";
      version = "2.4.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/livereload-js/-/livereload-js-2.4.0.tgz";
        sha512 = "XPQH8Z2GDP/Hwz2PCDrh2mth4yFejwA1OZ/81Ti3LgKyhDcEjsSsqFWZojHG0va/duGd+WyosY7eXLDoOyqcPw==";
      };
    };
    "lodash-4.17.21" = {
      name = "lodash";
      packageName = "lodash";
      version = "4.17.21";
      src = fetchurl {
        url = "https://registry.npmjs.org/lodash/-/lodash-4.17.21.tgz";
        sha512 = "v2kDEe57lecTulaDIuNTPy3Ry4gLGJ6Z1O3vE1krgXZNrsQ+LFTGHVxVjcXPs17LhbZVGedAJv8XZ1tvj5FvSg==";
      };
    };
    "make-dir-2.1.0" = {
      name = "make-dir";
      packageName = "make-dir";
      version = "2.1.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/make-dir/-/make-dir-2.1.0.tgz";
        sha512 = "LS9X+dc8KLxXCb8dni79fLIIUA5VyZoyjSMCwTluaXA0o27cCK0bhXkpgw+sTXVpPy/lSO57ilRixqk0vDmtRA==";
      };
    };
    "make-iterator-1.0.1" = {
      name = "make-iterator";
      packageName = "make-iterator";
      version = "1.0.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/make-iterator/-/make-iterator-1.0.1.tgz";
        sha512 = "pxiuXh0iVEq7VM7KMIhs5gxsfxCux2URptUQaXo4iZZJxBAzTPOLE2BumO5dbfVYq/hBJFBR/a1mFDmOx5AGmw==";
      };
    };
    "map-cache-0.2.2" = {
      name = "map-cache";
      packageName = "map-cache";
      version = "0.2.2";
      src = fetchurl {
        url = "https://registry.npmjs.org/map-cache/-/map-cache-0.2.2.tgz";
        sha512 = "8y/eV9QQZCiyn1SprXSrCmqJN0yNRATe+PO8ztwqrvrbdRLA3eYJF0yaR0YayLWkMbsQSKWS9N2gPcGEc4UsZg==";
      };
    };
    "micromatch-4.0.5" = {
      name = "micromatch";
      packageName = "micromatch";
      version = "4.0.5";
      src = fetchurl {
        url = "https://registry.npmjs.org/micromatch/-/micromatch-4.0.5.tgz";
        sha512 = "DMy+ERcEW2q8Z2Po+WNXuw3c5YaUSFjAO5GsJqfEl7UjvtIuFKO6ZrKvcItdy98dwFI2N1tg3zNIdKaQT+aNdA==";
      };
    };
    "mime-1.6.0" = {
      name = "mime";
      packageName = "mime";
      version = "1.6.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/mime/-/mime-1.6.0.tgz";
        sha512 = "x0Vn8spI+wuJ1O6S7gnbaQg8Pxh4NNHb7KSINmEWKiPE4RKOplvijn+NkmYmmRgP68mc70j2EbeTFRsrswaQeg==";
      };
    };
    "minimatch-3.0.8" = {
      name = "minimatch";
      packageName = "minimatch";
      version = "3.0.8";
      src = fetchurl {
        url = "https://registry.npmjs.org/minimatch/-/minimatch-3.0.8.tgz";
        sha512 = "6FsRAQsxQ61mw+qP1ZzbL9Bc78x2p5OqNgNpnoAFLTrX8n5Kxph0CsnhmKKNXTWjXqU5L0pGPR7hYk+XWZr60Q==";
      };
    };
    "minimist-0.0.10" = {
      name = "minimist";
      packageName = "minimist";
      version = "0.0.10";
      src = fetchurl {
        url = "https://registry.npmjs.org/minimist/-/minimist-0.0.10.tgz";
        sha512 = "iotkTvxc+TwOm5Ieim8VnSNvCDjCK9S8G3scJ50ZthspSxa7jx50jkhYduuAtAjvfDUwSgOwf8+If99AlOEhyw==";
      };
    };
    "mkdirp-1.0.4" = {
      name = "mkdirp";
      packageName = "mkdirp";
      version = "1.0.4";
      src = fetchurl {
        url = "https://registry.npmjs.org/mkdirp/-/mkdirp-1.0.4.tgz";
        sha512 = "vVqVZQyf3WLx2Shd0qJ9xuvqgAyKPLAiqITEtqW0oIUjzo3PePDd6fW9iFz30ef7Ysp/oiWqbhszeGWW2T6Gzw==";
      };
    };
    "module-deps-1.1.0" = {
      name = "module-deps";
      packageName = "module-deps";
      version = "1.1.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/module-deps/-/module-deps-1.1.0.tgz";
        sha512 = "4qswptt8+jZMqT+a6SOSfIrDjmlgQ9DTzl3iGdOoPa1SkGJZtje5Gc+g4+8F0NOW5fqyr6W8fhYc3IYEUK6FlA==";
      };
    };
    "ms-2.1.3" = {
      name = "ms";
      packageName = "ms";
      version = "2.1.3";
      src = fetchurl {
        url = "https://registry.npmjs.org/ms/-/ms-2.1.3.tgz";
        sha512 = "6FlzubTLZG3J2a/NVCAleEhjzq5oxgHyaCU9yYXvcLsvoVaHJq/s5xXI6/XXP6tz7R9xAOtHnSO/tXtF3WRTlA==";
      };
    };
    "needle-3.2.0" = {
      name = "needle";
      packageName = "needle";
      version = "3.2.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/needle/-/needle-3.2.0.tgz";
        sha512 = "oUvzXnyLiVyVGoianLijF9O/RecZUf7TkBfimjGrLM4eQhXyeJwM6GeAWccwfQ9aa4gMCZKqhAOuLaMIcQxajQ==";
      };
    };
    "nopt-3.0.6" = {
      name = "nopt";
      packageName = "nopt";
      version = "3.0.6";
      src = fetchurl {
        url = "https://registry.npmjs.org/nopt/-/nopt-3.0.6.tgz";
        sha512 = "4GUt3kSEYmk4ITxzB/b9vaIDfUVWN/Ml1Fwl11IlnIG2iaJ9O6WXZ9SrYM9NLI8OCBieN2Y8SWC2oJV0RQ7qYg==";
      };
    };
    "nopt-4.0.3" = {
      name = "nopt";
      packageName = "nopt";
      version = "4.0.3";
      src = fetchurl {
        url = "https://registry.npmjs.org/nopt/-/nopt-4.0.3.tgz";
        sha512 = "CvaGwVMztSMJLOeXPrez7fyfObdZqNUK1cPAEzLHrTybIua9pMdmmPR5YwtfNftIOMv3DPUhFaxsZMNTQO20Kg==";
      };
    };
    "object-assign-4.1.1" = {
      name = "object-assign";
      packageName = "object-assign";
      version = "4.1.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/object-assign/-/object-assign-4.1.1.tgz";
        sha512 = "rJgTQnkUnH1sFw8yT6VSU3zD3sWmu6sZhIseY8VX+GRu3P6F7Fu+JNDoXfklElbLJSnc3FUQHVe4cU5hj+BcUg==";
      };
    };
    "object-inspect-1.12.2" = {
      name = "object-inspect";
      packageName = "object-inspect";
      version = "1.12.2";
      src = fetchurl {
        url = "https://registry.npmjs.org/object-inspect/-/object-inspect-1.12.2.tgz";
        sha512 = "z+cPxW0QGUp0mcqcsgQyLVRDoXFQbXOwBaqyF7VIgI4TWNQsDHrBpUQslRmIfAoYWdYzs6UlKJtB2XJpTaNSpQ==";
      };
    };
    "object.defaults-1.1.0" = {
      name = "object.defaults";
      packageName = "object.defaults";
      version = "1.1.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/object.defaults/-/object.defaults-1.1.0.tgz";
        sha512 = "c/K0mw/F11k4dEUBMW8naXUuBuhxRCfG7W+yFy8EcijU/rSmazOUd1XAEEe6bC0OuXY4HUKjTJv7xbxIMqdxrA==";
      };
    };
    "object.map-1.0.1" = {
      name = "object.map";
      packageName = "object.map";
      version = "1.0.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/object.map/-/object.map-1.0.1.tgz";
        sha512 = "3+mAJu2PLfnSVGHwIWubpOFLscJANBKuB/6A4CxBstc4aqwQY0FWcsppuy4jU5GSB95yES5JHSI+33AWuS4k6w==";
      };
    };
    "object.pick-1.3.0" = {
      name = "object.pick";
      packageName = "object.pick";
      version = "1.3.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/object.pick/-/object.pick-1.3.0.tgz";
        sha512 = "tqa/UMy/CCoYmj+H5qc07qvSL9dqcs/WZENZ1JbtWBlATP+iVOe778gE6MSijnyCnORzDuX6hU+LA4SZ09YjFQ==";
      };
    };
    "once-1.4.0" = {
      name = "once";
      packageName = "once";
      version = "1.4.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/once/-/once-1.4.0.tgz";
        sha512 = "lNaJgI+2Q5URQBkccEKHTQOPaXdUxnZZElQTZY0MFUAuaEqe1E+Nyvgdz/aIyNi6Z9MzO5dv1H8n58/GELp3+w==";
      };
    };
    "optimist-0.3.7" = {
      name = "optimist";
      packageName = "optimist";
      version = "0.3.7";
      src = fetchurl {
        url = "https://registry.npmjs.org/optimist/-/optimist-0.3.7.tgz";
        sha512 = "TCx0dXQzVtSCg2OgY/bO9hjM9cV4XYx09TVK+s3+FhkjT6LovsLe+pPMzpWf+6yXK/hUizs2gUoTw3jHM0VaTQ==";
      };
    };
    "optimist-0.5.2" = {
      name = "optimist";
      packageName = "optimist";
      version = "0.5.2";
      src = fetchurl {
        url = "https://registry.npmjs.org/optimist/-/optimist-0.5.2.tgz";
        sha512 = "r9M8ZpnM9SXV5Wii7TCqienfcaY3tAiJe9Jchof87icbmbruKgK0xKXngmrnowTDnEawmmI1Qbha59JEoBkBGA==";
      };
    };
    "os-browserify-0.1.2" = {
      name = "os-browserify";
      packageName = "os-browserify";
      version = "0.1.2";
      src = fetchurl {
        url = "https://registry.npmjs.org/os-browserify/-/os-browserify-0.1.2.tgz";
        sha512 = "aZicJZccvxWOZ0Bja2eAch2L8RIJWBuRYmM8Gwl/JjNtRltH0Itcz4eH/ESyuIWfse8cc93ZCf0XrzhXK2HEDA==";
      };
    };
    "os-homedir-1.0.2" = {
      name = "os-homedir";
      packageName = "os-homedir";
      version = "1.0.2";
      src = fetchurl {
        url = "https://registry.npmjs.org/os-homedir/-/os-homedir-1.0.2.tgz";
        sha512 = "B5JU3cabzk8c67mRRd3ECmROafjYMXbuzlwtqdM8IbS8ktlTix8aFGb2bAGKrSRIlnfKwovGUUr72JUPyOb6kQ==";
      };
    };
    "os-tmpdir-1.0.2" = {
      name = "os-tmpdir";
      packageName = "os-tmpdir";
      version = "1.0.2";
      src = fetchurl {
        url = "https://registry.npmjs.org/os-tmpdir/-/os-tmpdir-1.0.2.tgz";
        sha512 = "D2FR03Vir7FIu45XBY20mTb+/ZSWB00sjU9jdQXt83gDrI4Ztz5Fs7/yy74g2N5SVQY4xY1qDr4rNddwYRVX0g==";
      };
    };
    "osenv-0.1.5" = {
      name = "osenv";
      packageName = "osenv";
      version = "0.1.5";
      src = fetchurl {
        url = "https://registry.npmjs.org/osenv/-/osenv-0.1.5.tgz";
        sha512 = "0CWcCECdMVc2Rw3U5w9ZjqX6ga6ubk1xDVKxtBQPK7wis/0F2r9T6k4ydGYhecl7YUBxBVxhL5oisPsNxAPe2g==";
      };
    };
    "parents-0.0.3" = {
      name = "parents";
      packageName = "parents";
      version = "0.0.3";
      src = fetchurl {
        url = "https://registry.npmjs.org/parents/-/parents-0.0.3.tgz";
        sha512 = "ASkdjFPS2nrxujzSBZGt8ZCKeG0/K2ZZVKveqXt7XGtXfu+ssnk4DQhnK91KRvt83f36LjfxOfwi0cv1+Re0eA==";
      };
    };
    "parse-filepath-1.0.2" = {
      name = "parse-filepath";
      packageName = "parse-filepath";
      version = "1.0.2";
      src = fetchurl {
        url = "https://registry.npmjs.org/parse-filepath/-/parse-filepath-1.0.2.tgz";
        sha512 = "FwdRXKCohSVeXqwtYonZTXtbGJKrn+HNyWDYVcp5yuJlesTwNH4rsmRZ+GrKAPJ5bLpRxESMeS+Rl0VCHRvB2Q==";
      };
    };
    "parse-node-version-1.0.1" = {
      name = "parse-node-version";
      packageName = "parse-node-version";
      version = "1.0.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/parse-node-version/-/parse-node-version-1.0.1.tgz";
        sha512 = "3YHlOa/JgH6Mnpr05jP9eDG254US9ek25LyIxZlDItp2iJtwyaXQb57lBYLdT3MowkUFYEV2XXNAYIPlESvJlA==";
      };
    };
    "parse-passwd-1.0.0" = {
      name = "parse-passwd";
      packageName = "parse-passwd";
      version = "1.0.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/parse-passwd/-/parse-passwd-1.0.0.tgz";
        sha512 = "1Y1A//QUXEZK7YKz+rD9WydcE1+EuPr6ZBgKecAB8tmoW6UFv0NREVJe1p+jRxtThkcbbKkfwIbWJe/IeE6m2Q==";
      };
    };
    "path-is-absolute-1.0.1" = {
      name = "path-is-absolute";
      packageName = "path-is-absolute";
      version = "1.0.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/path-is-absolute/-/path-is-absolute-1.0.1.tgz";
        sha512 = "AVbw3UJ2e9bq64vSaS9Am0fje1Pa8pbGqTTsmXfaIiMpnr5DlDhfJOuLj9Sf95ZPVDAUerDfEk88MPmPe7UCQg==";
      };
    };
    "path-parse-1.0.7" = {
      name = "path-parse";
      packageName = "path-parse";
      version = "1.0.7";
      src = fetchurl {
        url = "https://registry.npmjs.org/path-parse/-/path-parse-1.0.7.tgz";
        sha512 = "LDJzPVEEEPR+y48z93A0Ed0yXb8pAByGWo/k5YYdYgpY2/2EsOsksJrq7lOHxryrVOn1ejG6oAp8ahvOIQD8sw==";
      };
    };
    "path-platform-0.0.1" = {
      name = "path-platform";
      packageName = "path-platform";
      version = "0.0.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/path-platform/-/path-platform-0.0.1.tgz";
        sha512 = "ydK1VKZFYwy0mT2JvimJfxt5z6Z6sjBbLfsFMoJczbwZ/ul0AjgpXLHinUzclf4/XYC8mtsWGuFERZ95Rnm8wA==";
      };
    };
    "path-root-0.1.1" = {
      name = "path-root";
      packageName = "path-root";
      version = "0.1.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/path-root/-/path-root-0.1.1.tgz";
        sha512 = "QLcPegTHF11axjfojBIoDygmS2E3Lf+8+jI6wOVmNVenrKSo3mFdSGiIgdSHenczw3wPtlVMQaFVwGmM7BJdtg==";
      };
    };
    "path-root-regex-0.1.2" = {
      name = "path-root-regex";
      packageName = "path-root-regex";
      version = "0.1.2";
      src = fetchurl {
        url = "https://registry.npmjs.org/path-root-regex/-/path-root-regex-0.1.2.tgz";
        sha512 = "4GlJ6rZDhQZFE0DPVKh0e9jmZ5egZfxTkp7bcRDuPlJXbAwhxcl2dINPUAsjLdejqaLsCeg8axcLjIbvBjN4pQ==";
      };
    };
    "pica-1.1.1" = {
      name = "pica";
      packageName = "pica";
      version = "1.1.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/pica/-/pica-1.1.1.tgz";
        sha512 = "EllPo0f871ZEYMWMyNSd5wF2hss1Uvy7fgRh0PmaEtmzIdeEW9UobxqqiWUZrw+YdlCaghF0PYtQ0WM66ikvKQ==";
      };
    };
    "picomatch-2.3.1" = {
      name = "picomatch";
      packageName = "picomatch";
      version = "2.3.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/picomatch/-/picomatch-2.3.1.tgz";
        sha512 = "JU3teHTNjmE2VCGFzuY8EXzCDVwEqB2a8fsIvwaStHhAWJEeVd1o1QD80CU6+ZdEXXSLbSsuLwJjkCBWqRQUVA==";
      };
    };
    "pify-4.0.1" = {
      name = "pify";
      packageName = "pify";
      version = "4.0.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/pify/-/pify-4.0.1.tgz";
        sha512 = "uB80kBFb/tfd68bVleG9T5GGsGPjJrLAUpR5PZIrhBnIaRTQRjqdJSsIKkOP6OAIFbj7GOrcudc5pNjZ+geV2g==";
      };
    };
    "process-0.5.2" = {
      name = "process";
      packageName = "process";
      version = "0.5.2";
      src = fetchurl {
        url = "https://registry.npmjs.org/process/-/process-0.5.2.tgz";
        sha512 = "oNpcutj+nYX2FjdEW7PGltWhXulAnFlM0My/k48L90hARCOJtvBbQXc/6itV2jDvU5xAAtonP+r6wmQgCcbAUA==";
      };
    };
    "prr-1.0.1" = {
      name = "prr";
      packageName = "prr";
      version = "1.0.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/prr/-/prr-1.0.1.tgz";
        sha512 = "yPw4Sng1gWghHQWj0B3ZggWUm4qVbPwPFcRG8KyxiU7J2OHFSoEHKS+EZ3fv5l1t9CyCiop6l/ZYeWbrgoQejw==";
      };
    };
    "punycode-1.2.4" = {
      name = "punycode";
      packageName = "punycode";
      version = "1.2.4";
      src = fetchurl {
        url = "https://registry.npmjs.org/punycode/-/punycode-1.2.4.tgz";
        sha512 = "h/vscxLPvI2l7k/0dFUKZ5I5TgMCJ/Pl+J6rw77PDuQM6UApf/GaRVkjv/YSm2k+fbp7Yw8dxsoe29DolT7h7w==";
      };
    };
    "qs-6.11.0" = {
      name = "qs";
      packageName = "qs";
      version = "6.11.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/qs/-/qs-6.11.0.tgz";
        sha512 = "MvjoMCJwEarSbUYk5O+nmoSzSutSsTwF85zcHPQ9OrlFoZOYIjaqBAJIqIXjptyD5vThxGq52Xu/MaJzRkIk4Q==";
      };
    };
    "raw-body-1.1.7" = {
      name = "raw-body";
      packageName = "raw-body";
      version = "1.1.7";
      src = fetchurl {
        url = "https://registry.npmjs.org/raw-body/-/raw-body-1.1.7.tgz";
        sha512 = "WmJJU2e9Y6M5UzTOkHaM7xJGAPQD8PNzx3bAd2+uhZAim6wDk6dAZxPVYLF67XhbR4hmKGh33Lpmh4XWrCH5Mg==";
      };
    };
    "readable-stream-1.1.14" = {
      name = "readable-stream";
      packageName = "readable-stream";
      version = "1.1.14";
      src = fetchurl {
        url = "https://registry.npmjs.org/readable-stream/-/readable-stream-1.1.14.tgz";
        sha512 = "+MeVjFf4L44XUkhM1eYbD8fyEsxcV81pqMSR5gblfcLCHfZvbrqy4/qYHE+/R5HoBUT11WV5O08Cr1n3YXkWVQ==";
      };
    };
    "rechoir-0.7.1" = {
      name = "rechoir";
      packageName = "rechoir";
      version = "0.7.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/rechoir/-/rechoir-0.7.1.tgz";
        sha512 = "/njmZ8s1wVeR6pjTZ+0nCnv8SpZNRMT2D1RLOJQESlYFDBvwpTA4KWJpZ+sBJ4+vhjILRcK7JIFdGCdxEAAitg==";
      };
    };
    "resolve-0.3.1" = {
      name = "resolve";
      packageName = "resolve";
      version = "0.3.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/resolve/-/resolve-0.3.1.tgz";
        sha512 = "mxx/I/wLjxtryDBtrrb0ZNzaYERVWaHpJ0W0Arm8N4l8b+jiX/U5yKcsj0zQpF9UuKN1uz80EUTOudON6OPuaQ==";
      };
    };
    "resolve-0.6.3" = {
      name = "resolve";
      packageName = "resolve";
      version = "0.6.3";
      src = fetchurl {
        url = "https://registry.npmjs.org/resolve/-/resolve-0.6.3.tgz";
        sha512 = "UHBY3viPlJKf85YijDUcikKX6tmF4SokIDp518ZDVT92JNDcG5uKIthaT/owt3Sar0lwtOafsQuwrg22/v2Dwg==";
      };
    };
    "resolve-1.22.1" = {
      name = "resolve";
      packageName = "resolve";
      version = "1.22.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/resolve/-/resolve-1.22.1.tgz";
        sha512 = "nBpuuYuY5jFsli/JIs1oldw6fOQCBioohqWZg/2hiaOybXOft4lonv85uDOKXdf8rhyK159cxU5cDcK/NKk8zw==";
      };
    };
    "resolve-dir-1.0.1" = {
      name = "resolve-dir";
      packageName = "resolve-dir";
      version = "1.0.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/resolve-dir/-/resolve-dir-1.0.1.tgz";
        sha512 = "R7uiTjECzvOsWSfdM0QKFNBVFcK27aHOUwdvK53BcW8zqnGdYp0Fbj82cy54+2A4P2tFM22J5kRfe1R+lM/1yg==";
      };
    };
    "rfile-1.0.0" = {
      name = "rfile";
      packageName = "rfile";
      version = "1.0.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/rfile/-/rfile-1.0.0.tgz";
        sha512 = "aNeTpY8g6DYmqPvakau22B0SipQTskO8FtYXzn8qg4X4bN9ExIH8VAhq/L9w7N8HvESYeSSwk3e4GmW+rLLAxQ==";
      };
    };
    "rimraf-3.0.2" = {
      name = "rimraf";
      packageName = "rimraf";
      version = "3.0.2";
      src = fetchurl {
        url = "https://registry.npmjs.org/rimraf/-/rimraf-3.0.2.tgz";
        sha512 = "JZkJMZkAGFFPP2YqXZXPbMlMBgsxzE8ILs4lMIX/2o0L9UBw9O/Y3o6wFw/i9YLapcUJWwqbi3kdxIPdC62TIA==";
      };
    };
    "ruglify-1.0.0" = {
      name = "ruglify";
      packageName = "ruglify";
      version = "1.0.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/ruglify/-/ruglify-1.0.0.tgz";
        sha512 = "XfRj1YJdm/gnZNvmpQ5L+2YGRHglDGMPgJRbitgCxC3GzKVQF/t+ij1aNcNg2AnEXGtLHJDwoSWrAq3TUm0EVg==";
      };
    };
    "safe-buffer-5.2.1" = {
      name = "safe-buffer";
      packageName = "safe-buffer";
      version = "5.2.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/safe-buffer/-/safe-buffer-5.2.1.tgz";
        sha512 = "rp3So07KcdmmKbGvgaNxQSJr7bGVSVk5S9Eq1F+ppbRo70+YeaDxkw5Dd8NPN+GD6bjnYm2VuPuCXmpuYvmCXQ==";
      };
    };
    "safe-json-parse-1.0.1" = {
      name = "safe-json-parse";
      packageName = "safe-json-parse";
      version = "1.0.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/safe-json-parse/-/safe-json-parse-1.0.1.tgz";
        sha512 = "o0JmTu17WGUaUOHa1l0FPGXKBfijbxK6qoHzlkihsDXxzBHvJcA7zgviKR92Xs841rX9pK16unfphLq0/KqX7A==";
      };
    };
    "safer-buffer-2.1.2" = {
      name = "safer-buffer";
      packageName = "safer-buffer";
      version = "2.1.2";
      src = fetchurl {
        url = "https://registry.npmjs.org/safer-buffer/-/safer-buffer-2.1.2.tgz";
        sha512 = "YZo3K82SD7Riyi0E1EQPojLz7kpepnSQI9IyPbHHg1XXXevb5dJI7tpyN2ADxGcQbHG7vcyRHk0cbwqcQriUtg==";
      };
    };
    "sax-1.2.4" = {
      name = "sax";
      packageName = "sax";
      version = "1.2.4";
      src = fetchurl {
        url = "https://registry.npmjs.org/sax/-/sax-1.2.4.tgz";
        sha512 = "NqVDv9TpANUjFm0N8uM5GxL36UgKi9/atZw+x7YFnQ8ckwFGKrl4xX4yWtrey3UJm5nP1kUbnYgLopqWNSRhWw==";
      };
    };
    "semver-5.7.1" = {
      name = "semver";
      packageName = "semver";
      version = "5.7.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/semver/-/semver-5.7.1.tgz";
        sha512 = "sauaDf/PZdVgrLTNYHRtpXa1iRiKcaebiKQ1BJdpQlWH2lCvexQdX55snPFyK7QzpudqbCI0qXFfOasHdyNDGQ==";
      };
    };
    "shell-quote-0.0.1" = {
      name = "shell-quote";
      packageName = "shell-quote";
      version = "0.0.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/shell-quote/-/shell-quote-0.0.1.tgz";
        sha512 = "uEWz7wa9vnCi9w4mvKZMgbHFk3DCKjLQlZcy0tJxUH4NwZjRrPPHXAYIEt2TmJs600Dcgj0Z3fZLZKVPVdGNbQ==";
      };
    };
    "side-channel-1.0.4" = {
      name = "side-channel";
      packageName = "side-channel";
      version = "1.0.4";
      src = fetchurl {
        url = "https://registry.npmjs.org/side-channel/-/side-channel-1.0.4.tgz";
        sha512 = "q5XPytqFEIKHkGdiMIrY10mvLRvnQh42/+GoBlFW3b2LXLE2xxJpZFdm94we0BaoV3RwJyGqg5wS7epxTv0Zvw==";
      };
    };
    "source-map-0.1.34" = {
      name = "source-map";
      packageName = "source-map";
      version = "0.1.34";
      src = fetchurl {
        url = "https://registry.npmjs.org/source-map/-/source-map-0.1.34.tgz";
        sha512 = "yfCwDj0vR9RTwt3pEzglgb3ZgmcXHt6DjG3bjJvzPwTL+5zDQ2MhmSzAcTy0GTiQuCiriSWXvWM1/NhKdXuoQA==";
      };
    };
    "source-map-0.1.43" = {
      name = "source-map";
      packageName = "source-map";
      version = "0.1.43";
      src = fetchurl {
        url = "https://registry.npmjs.org/source-map/-/source-map-0.1.43.tgz";
        sha512 = "VtCvB9SIQhk3aF6h+N85EaqIaBFIAfZ9Cu+NJHHVvc8BbEcnvDcFw6sqQ2dQrT6SlOrZq3tIvyD9+EGq/lJryQ==";
      };
    };
    "source-map-0.3.0" = {
      name = "source-map";
      packageName = "source-map";
      version = "0.3.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/source-map/-/source-map-0.3.0.tgz";
        sha512 = "jz8leTIGS8+qJywWiO9mKza0hJxexdeIYXhDHw9avTQcXSNAGk3hiiRMpmI2Qf9dOrZDrDpgH9VNefzuacWC9A==";
      };
    };
    "source-map-0.6.1" = {
      name = "source-map";
      packageName = "source-map";
      version = "0.6.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/source-map/-/source-map-0.6.1.tgz";
        sha512 = "UjgapumWlbMhkBgzT7Ykc5YXUT46F0iKu8SGXq0bcwP5dz/h0Plj6enJqjz1Zbq2l5WaqYnrVbwWOWMyF3F47g==";
      };
    };
    "sprintf-js-1.0.3" = {
      name = "sprintf-js";
      packageName = "sprintf-js";
      version = "1.0.3";
      src = fetchurl {
        url = "https://registry.npmjs.org/sprintf-js/-/sprintf-js-1.0.3.tgz";
        sha512 = "D9cPgkvLlV3t3IzL0D0YLvGA9Ahk4PcvVwUbN0dSGr1aP0Nrt4AEnTUbuGvquEC0mA64Gqt1fzirlRs5ibXx8g==";
      };
    };
    "sprintf-js-1.1.2" = {
      name = "sprintf-js";
      packageName = "sprintf-js";
      version = "1.1.2";
      src = fetchurl {
        url = "https://registry.npmjs.org/sprintf-js/-/sprintf-js-1.1.2.tgz";
        sha512 = "VE0SOVEHCk7Qc8ulkWw3ntAzXuqf7S2lvwQaDLRnUeIEaKNQJzV6BwmLKhOqT61aGhfUMrXeaBk+oDGCzvhcug==";
      };
    };
    "stream-combiner-0.0.4" = {
      name = "stream-combiner";
      packageName = "stream-combiner";
      version = "0.0.4";
      src = fetchurl {
        url = "https://registry.npmjs.org/stream-combiner/-/stream-combiner-0.0.4.tgz";
        sha512 = "rT00SPnTVyRsaSz5zgSPma/aHSOic5U1prhYdRy5HS2kTZviFpmDgzilbtsJsxiroqACmayynDN/9VzIbX5DOw==";
      };
    };
    "string-template-0.2.1" = {
      name = "string-template";
      packageName = "string-template";
      version = "0.2.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/string-template/-/string-template-0.2.1.tgz";
        sha512 = "Yptehjogou2xm4UJbxJ4CxgZx12HBfeystp0y3x7s4Dj32ltVVG1Gg8YhKjHZkHicuKpZX/ffilA8505VbUbpw==";
      };
    };
    "string_decoder-0.10.31" = {
      name = "string_decoder";
      packageName = "string_decoder";
      version = "0.10.31";
      src = fetchurl {
        url = "https://registry.npmjs.org/string_decoder/-/string_decoder-0.10.31.tgz";
        sha512 = "ev2QzSzWPYmy9GuqfIVildA4OdcGLeFZQrq5ys6RtiuF+RQQiZWr8TZNyAcuVXyQRYfEO+MsoB/1BuQVhOJuoQ==";
      };
    };
    "strip-json-comments-1.0.4" = {
      name = "strip-json-comments";
      packageName = "strip-json-comments";
      version = "1.0.4";
      src = fetchurl {
        url = "https://registry.npmjs.org/strip-json-comments/-/strip-json-comments-1.0.4.tgz";
        sha512 = "AOPG8EBc5wAikaG1/7uFCNFJwnKOuQwFTpYBdTW6OvWHeZBQBrAA/amefHGrEiOnCPcLFZK6FUPtWVKpQVIRgg==";
      };
    };
    "supports-color-7.2.0" = {
      name = "supports-color";
      packageName = "supports-color";
      version = "7.2.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/supports-color/-/supports-color-7.2.0.tgz";
        sha512 = "qpCAvRl9stuOHveKsn7HncJRvv501qIacKzQlO/+Lwxc9+0q2wLyv4Dfvt80/DPn2pqOBsJdDiogXGR9+OvwRw==";
      };
    };
    "supports-preserve-symlinks-flag-1.0.0" = {
      name = "supports-preserve-symlinks-flag";
      packageName = "supports-preserve-symlinks-flag";
      version = "1.0.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/supports-preserve-symlinks-flag/-/supports-preserve-symlinks-flag-1.0.0.tgz";
        sha512 = "ot0WnXS9fgdkgIcePe6RHNk1WA8+muPa6cSjeR3V8K27q9BB1rTE3R1p7Hv0z1ZyAc8s6Vvv8DIyWf681MAt0w==";
      };
    };
    "syntax-error-0.0.1" = {
      name = "syntax-error";
      packageName = "syntax-error";
      version = "0.0.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/syntax-error/-/syntax-error-0.0.1.tgz";
        sha512 = "Pg2FzUaDR1Zlkl5ol+6LGAES7PjqcvfUpa2OKZZhww4VrRyjZyU2v+4C0dcYfhwNl2FMaZW9mXHzX0kS9x3xXw==";
      };
    };
    "tape-0.2.2" = {
      name = "tape";
      packageName = "tape";
      version = "0.2.2";
      src = fetchurl {
        url = "https://registry.npmjs.org/tape/-/tape-0.2.2.tgz";
        sha512 = "bfyf/0yv2FZVsf80b7oo50Lyi35sfjE7VM6206du7LtpbdQP8rbLhZy/stuS/Dcq4w6jE1Pz2zFrHtfeOKbaUA==";
      };
    };
    "through-2.2.7" = {
      name = "through";
      packageName = "through";
      version = "2.2.7";
      src = fetchurl {
        url = "https://registry.npmjs.org/through/-/through-2.2.7.tgz";
        sha512 = "JIR0m0ybkmTcR8URann+HbwKmodP+OE8UCbsifQDYMLD5J3em1Cdn3MYPpbEd5elGDwmP98T+WbqP/tvzA5Mjg==";
      };
    };
    "through-2.3.8" = {
      name = "through";
      packageName = "through";
      version = "2.3.8";
      src = fetchurl {
        url = "https://registry.npmjs.org/through/-/through-2.3.8.tgz";
        sha512 = "w89qg7PI8wAdvX60bMDP+bFoD5Dvhm9oLheFp5O4a2QF0cSBGsBX4qZmadPMvVqlLJBBci+WqGGOAPvcDeNSVg==";
      };
    };
    "tiny-lr-1.1.1" = {
      name = "tiny-lr";
      packageName = "tiny-lr";
      version = "1.1.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/tiny-lr/-/tiny-lr-1.1.1.tgz";
        sha512 = "44yhA3tsaRoMOjQQ+5v5mVdqef+kH6Qze9jTpqtVufgYjYt08zyZAwNwwVBj3i1rJMnR52IxOW0LK0vBzgAkuA==";
      };
    };
    "to-regex-range-5.0.1" = {
      name = "to-regex-range";
      packageName = "to-regex-range";
      version = "5.0.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/to-regex-range/-/to-regex-range-5.0.1.tgz";
        sha512 = "65P7iz6X5yEr1cwcgvQxbbIw7Uk3gOy5dIdtZ4rDveLqhrdJP+Li/Hx6tyK0NEb+2GCyneCMJiGqrADCSNk8sQ==";
      };
    };
    "to-utf8-0.0.1" = {
      name = "to-utf8";
      packageName = "to-utf8";
      version = "0.0.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/to-utf8/-/to-utf8-0.0.1.tgz";
        sha512 = "zks18/TWT1iHO3v0vFp5qLKOG27m67ycq/Y7a7cTiRuUNlc4gf3HGnkRgMv0NyhnfTamtkYBJl+YeD1/j07gBQ==";
      };
    };
    "tslib-2.4.1" = {
      name = "tslib";
      packageName = "tslib";
      version = "2.4.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/tslib/-/tslib-2.4.1.tgz";
        sha512 = "tGyy4dAjRIEwI7BzsB0lynWgOpfqjUdq91XXAlIWD2OwKBH7oCl/GZG/HT4BOHrTlPMOASlMQ7veyTqpmRcrNA==";
      };
    };
    "uglify-js-2.2.5" = {
      name = "uglify-js";
      packageName = "uglify-js";
      version = "2.2.5";
      src = fetchurl {
        url = "https://registry.npmjs.org/uglify-js/-/uglify-js-2.2.5.tgz";
        sha512 = "viLk+/8G0zm2aKt1JJAVcz5J/5ytdiNaIsKgrre3yvSUjwVG6ZUujGH7E2TiPigZUwLYCe7eaIUEP2Zka2VJPA==";
      };
    };
    "uglify-js-2.4.24" = {
      name = "uglify-js";
      packageName = "uglify-js";
      version = "2.4.24";
      src = fetchurl {
        url = "https://registry.npmjs.org/uglify-js/-/uglify-js-2.4.24.tgz";
        sha512 = "tktIjwackfZLd893KGJmXc1hrRHH1vH9Po3xFh1XBjjeGAnN02xJ3SuoA+n1L29/ZaCA18KzCFlckS+vfPugiA==";
      };
    };
    "uglify-to-browserify-1.0.2" = {
      name = "uglify-to-browserify";
      packageName = "uglify-to-browserify";
      version = "1.0.2";
      src = fetchurl {
        url = "https://registry.npmjs.org/uglify-to-browserify/-/uglify-to-browserify-1.0.2.tgz";
        sha512 = "vb2s1lYx2xBtUgy+ta+b2J/GLVUR+wmpINwHePmPRhOsIVCG2wDzKJ0n14GslH1BifsqVzSOwQhRaCAsZ/nI4Q==";
      };
    };
    "umd-1.3.1" = {
      name = "umd";
      packageName = "umd";
      version = "1.3.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/umd/-/umd-1.3.1.tgz";
        sha512 = "twQRbJVFlTOl6qVc065yaBDEo/ZoypRAi7v1kMjACN0RrlzuDQ1lHwrfZVLzQciQt2ZDJEhqLo5+LvwwHshS8w==";
      };
    };
    "unc-path-regex-0.1.2" = {
      name = "unc-path-regex";
      packageName = "unc-path-regex";
      version = "0.1.2";
      src = fetchurl {
        url = "https://registry.npmjs.org/unc-path-regex/-/unc-path-regex-0.1.2.tgz";
        sha512 = "eXL4nmJT7oCpkZsHZUOJo8hcX3GbsiDOa0Qu9F646fi8dT3XuSVopVqAcEiVzSKKH7UoDti23wNX3qGFxcW5Qg==";
      };
    };
    "underscore.string-3.3.6" = {
      name = "underscore.string";
      packageName = "underscore.string";
      version = "3.3.6";
      src = fetchurl {
        url = "https://registry.npmjs.org/underscore.string/-/underscore.string-3.3.6.tgz";
        sha512 = "VoC83HWXmCrF6rgkyxS9GHv8W9Q5nhMKho+OadDJGzL2oDYbYEppBaCMH6pFlwLeqj2QS+hhkw2kpXkSdD1JxQ==";
      };
    };
    "util-deprecate-1.0.2" = {
      name = "util-deprecate";
      packageName = "util-deprecate";
      version = "1.0.2";
      src = fetchurl {
        url = "https://registry.npmjs.org/util-deprecate/-/util-deprecate-1.0.2.tgz";
        sha512 = "EPD5q1uXyFxJpCrLnCc1nHnq3gOa6DZBocAIiI2TaSCA7VCJ1UJDMagCzIkXNsUYfD1daK//LTEQ8xiIbrHtcw==";
      };
    };
    "v8flags-3.2.0" = {
      name = "v8flags";
      packageName = "v8flags";
      version = "3.2.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/v8flags/-/v8flags-3.2.0.tgz";
        sha512 = "mH8etigqMfiGWdeXpaaqGfs6BndypxusHHcv2qSHyZkGEznCd/qAXCWWRzeowtL54147cktFOC4P5y+kl8d8Jg==";
      };
    };
    "vm-browserify-0.0.4" = {
      name = "vm-browserify";
      packageName = "vm-browserify";
      version = "0.0.4";
      src = fetchurl {
        url = "https://registry.npmjs.org/vm-browserify/-/vm-browserify-0.0.4.tgz";
        sha512 = "NyZNR3WDah+NPkjh/YmhuWSsT4a0mF0BJYgUmvrJ70zxjTXh5Y2Asobxlh0Nfs0PCFB5FVpRJft7NozAWFMwLQ==";
      };
    };
    "vtf-0.0.3" = {
      name = "vtf";
      packageName = "vtf";
      version = "0.0.3";
      src = fetchurl {
        url = "https://registry.npmjs.org/vtf/-/vtf-0.0.3.tgz";
        sha512 = "6C/qZ7bJ68bTzAfnRL32hb2nbepPnmkAaSvT3C9t7xQZYuXqBVa7CWi3nfyKRj/Pr4/W+Cira5XXvt7iD3+cJw==";
      };
    };
    "websocket-driver-0.7.4" = {
      name = "websocket-driver";
      packageName = "websocket-driver";
      version = "0.7.4";
      src = fetchurl {
        url = "https://registry.npmjs.org/websocket-driver/-/websocket-driver-0.7.4.tgz";
        sha512 = "b17KeDIQVjvb0ssuSDF2cYXSg2iztliJ4B9WdsuB6J952qCPKmnVq4DyW5motImXHDC1cBT/1UezrJVsKw5zjg==";
      };
    };
    "websocket-extensions-0.1.4" = {
      name = "websocket-extensions";
      packageName = "websocket-extensions";
      version = "0.1.4";
      src = fetchurl {
        url = "https://registry.npmjs.org/websocket-extensions/-/websocket-extensions-0.1.4.tgz";
        sha512 = "OqedPIGOfsDlo31UNwYbCFMSaO9m9G/0faIHj5/dZFDMFqPTcx6UwqyOy3COEaEOg/9VsGIpdqn62W5KhoKSpg==";
      };
    };
    "webworkify-1.0.2" = {
      name = "webworkify";
      packageName = "webworkify";
      version = "1.0.2";
      src = fetchurl {
        url = "https://registry.npmjs.org/webworkify/-/webworkify-1.0.2.tgz";
        sha512 = "gB3Dgc0yeR5heUyamGw5EGERTxfqKvQClKkP1tmCpNThCVa/bkiue2+x6OSPmsoWGUZy+i1CfQenjyKyyfR42g==";
      };
    };
    "which-1.3.1" = {
      name = "which";
      packageName = "which";
      version = "1.3.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/which/-/which-1.3.1.tgz";
        sha512 = "HxJdYWq1MTIQbJ3nw0cqssHoTNU267KlrDuGZ1WYlxDStUtKUhOaJmh112/TZmHxxUfuJqPXSOm7tDyas0OSIQ==";
      };
    };
    "which-2.0.2" = {
      name = "which";
      packageName = "which";
      version = "2.0.2";
      src = fetchurl {
        url = "https://registry.npmjs.org/which/-/which-2.0.2.tgz";
        sha512 = "BLI3Tl1TW3Pvl70l3yq3Y64i+awpwXqsGBYWkkqMtnbXgrMD+yj7rhW0kuEDxzJaYXGjEW5ogapKNMEKNMjibA==";
      };
    };
    "window-size-0.1.0" = {
      name = "window-size";
      packageName = "window-size";
      version = "0.1.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/window-size/-/window-size-0.1.0.tgz";
        sha512 = "1pTPQDKTdd61ozlKGNCjhNRd+KPmgLSGa3mZTHoOliaGcESD8G1PXhh7c1fgiPjVbNVfgy2Faw4BI8/m0cC8Mg==";
      };
    };
    "wordwrap-0.0.2" = {
      name = "wordwrap";
      packageName = "wordwrap";
      version = "0.0.2";
      src = fetchurl {
        url = "https://registry.npmjs.org/wordwrap/-/wordwrap-0.0.2.tgz";
        sha512 = "xSBsCeh+g+dinoBv3GAOWM4LcVVO68wLXRanibtBSdUvkGWQRGeE9P7IwU9EmDDi4jA6L44lz15CGMwdw9N5+Q==";
      };
    };
    "wordwrap-0.0.3" = {
      name = "wordwrap";
      packageName = "wordwrap";
      version = "0.0.3";
      src = fetchurl {
        url = "https://registry.npmjs.org/wordwrap/-/wordwrap-0.0.3.tgz";
        sha512 = "1tMA907+V4QmxV7dbRvb4/8MaRALK6q9Abid3ndMYnbyo8piisCmeONVqVSXqQA3KaP4SLt5b7ud6E2sqP8TFw==";
      };
    };
    "wrappy-1.0.2" = {
      name = "wrappy";
      packageName = "wrappy";
      version = "1.0.2";
      src = fetchurl {
        url = "https://registry.npmjs.org/wrappy/-/wrappy-1.0.2.tgz";
        sha512 = "l4Sp/DRseor9wL6EvV2+TuQn63dMkPjZ/sp9XkghTEbV9KlPS1xUsZ3u7/IQO4wxtcFB4bgpQPRcR3QCvezPcQ==";
      };
    };
    "yargs-3.5.4" = {
      name = "yargs";
      packageName = "yargs";
      version = "3.5.4";
      src = fetchurl {
        url = "https://registry.npmjs.org/yargs/-/yargs-3.5.4.tgz";
        sha512 = "5j382E4xQSs71p/xZQsU1PtRA2HXPAjX0E0DkoGLxwNASMOKX6A9doV1NrZmj85u2Pjquz402qonBzz/yLPbPA==";
      };
    };
    "zlib-browserify-0.0.3" = {
      name = "zlib-browserify";
      packageName = "zlib-browserify";
      version = "0.0.3";
      src = fetchurl {
        url = "https://registry.npmjs.org/zlib-browserify/-/zlib-browserify-0.0.3.tgz";
        sha512 = "KW42YGoQKq7+oU46deeWMUsrPyBruEWV1DoObBTMfEC2LnTqQIrwKVKrPoz2mn5DXESW4Ca/lIP2MqGHrt/WFA==";
      };
    };
  };
  args = {
    name = "sprays.tf";
    packageName = "sprays.tf";
    version = "0.0.1";
    src = ./.;
    dependencies = [
      sources."Base64-0.1.4"
      (sources."JSONStream-0.6.4"
        // {
          dependencies = [
            sources."through-2.2.7"
          ];
        })
      sources."abbrev-1.1.1"
      sources."amdefine-1.0.1"
      sources."ansi-styles-4.3.0"
      (sources."argparse-1.0.10"
        // {
          dependencies = [
            sources."sprintf-js-1.0.3"
          ];
        })
      sources."array-each-1.0.1"
      sources."array-slice-1.1.0"
      (sources."astw-0.0.0"
        // {
          dependencies = [
            sources."esprima-1.0.2"
          ];
        })
      sources."async-3.2.4"
      sources."balanced-match-1.0.2"
      sources."base64-js-0.0.8"
      sources."bluebird-3.7.2"
      sources."body-5.1.0"
      (sources."bops-0.0.6"
        // {
          dependencies = [
            sources."base64-js-0.0.2"
          ];
        })
      sources."brace-expansion-1.1.11"
      sources."braces-3.0.2"
      (sources."browser-builtins-2.0.5"
        // {
          dependencies = [
            sources."console-browserify-1.0.3"
          ];
        })
      sources."browser-filesaver-1.1.1"
      sources."browser-pack-1.1.0"
      (sources."browser-resolve-1.2.4"
        // {
          dependencies = [
            sources."resolve-0.6.3"
          ];
        })
      (sources."browserify-2.36.1"
        // {
          dependencies = [
            sources."inherits-1.0.2"
          ];
        })
      sources."buffer-browserify-0.2.5"
      sources."bytes-1.0.0"
      sources."call-bind-1.0.2"
      sources."callsite-1.0.0"
      sources."camelcase-1.2.1"
      sources."chalk-4.1.2"
      sources."cli-1.0.1"
      sources."color-convert-2.0.1"
      sources."color-name-1.1.4"
      sources."colors-1.1.2"
      (sources."combine-source-map-0.3.0"
        // {
          dependencies = [
            sources."source-map-0.1.43"
          ];
        })
      sources."commondir-0.0.2"
      sources."concat-map-0.0.1"
      sources."concat-stream-1.0.1"
      sources."console-browserify-1.1.0"
      sources."constants-browserify-0.0.1"
      sources."continuable-cache-0.3.1"
      sources."convert-source-map-0.3.5"
      sources."copy-anything-2.0.6"
      sources."core-util-is-1.0.3"
      sources."crypto-browserify-1.0.9"
      sources."date-now-0.1.4"
      sources."dateformat-3.0.3"
      sources."debug-3.2.7"
      sources."decamelize-1.2.0"
      sources."deep-equal-0.1.2"
      sources."defined-0.0.0"
      sources."deps-sort-0.1.2"
      sources."detect-file-1.0.0"
      (sources."detective-2.1.2"
        // {
          dependencies = [
            sources."esprima-1.0.2"
          ];
        })
      (sources."dom-serializer-0.2.2"
        // {
          dependencies = [
            sources."domelementtype-2.3.0"
            sources."entities-2.2.0"
          ];
        })
      sources."domelementtype-1.3.1"
      sources."domhandler-2.3.0"
      sources."domready-1.0.8"
      sources."domutils-1.5.1"
      sources."duplexer-0.1.2"
      sources."entities-1.0.0"
      sources."errno-0.1.8"
      sources."error-7.2.1"
      sources."escodegen-0.0.15"
      sources."esprima-4.0.1"
      sources."eventemitter2-0.4.14"
      sources."exit-0.1.2"
      sources."expand-tilde-2.0.2"
      sources."extend-3.0.2"
      sources."faye-websocket-0.10.0"
      sources."fill-range-7.0.1"
      (sources."findup-sync-0.3.0"
        // {
          dependencies = [
            sources."glob-5.0.15"
          ];
        })
      sources."fined-1.2.0"
      sources."flagged-respawn-1.0.1"
      sources."for-in-1.0.2"
      sources."for-own-1.0.0"
      sources."fs.realpath-1.0.0"
      sources."function-bind-1.1.1"
      sources."gaze-1.1.3"
      sources."get-intrinsic-1.1.3"
      sources."getobject-1.0.2"
      sources."glob-7.1.7"
      sources."global-modules-1.0.0"
      sources."global-prefix-1.0.2"
      sources."globule-1.3.4"
      sources."glur-1.1.2"
      sources."graceful-fs-4.2.10"
      sources."grunt-1.5.3"
      sources."grunt-asset-cachebuster-0.5.0"
      (sources."grunt-cli-1.4.3"
        // {
          dependencies = [
            sources."nopt-4.0.3"
          ];
        })
      sources."grunt-contrib-jshint-3.2.0"
      sources."grunt-contrib-less-3.0.0"
      (sources."grunt-contrib-watch-1.1.0"
        // {
          dependencies = [
            sources."async-2.6.4"
          ];
        })
      sources."grunt-known-options-2.0.0"
      sources."grunt-legacy-log-3.0.0"
      sources."grunt-legacy-log-utils-2.1.0"
      (sources."grunt-legacy-util-2.0.1"
        // {
          dependencies = [
            sources."which-2.0.2"
          ];
        })
      sources."grunt-watchify-0.1.0"
      sources."has-1.0.3"
      sources."has-flag-4.0.0"
      sources."has-symbols-1.0.3"
      sources."homedir-polyfill-1.0.3"
      sources."hooker-0.2.3"
      sources."htmlparser2-3.8.3"
      sources."http-browserify-0.1.14"
      sources."http-parser-js-0.5.8"
      sources."iconv-lite-0.4.24"
      sources."image-size-0.5.5"
      sources."indexof-0.0.1"
      sources."inflight-1.0.6"
      sources."inherits-2.0.4"
      sources."ini-1.3.8"
      (sources."inline-source-map-0.3.1"
        // {
          dependencies = [
            sources."source-map-0.3.0"
          ];
        })
      (sources."insert-module-globals-1.3.1"
        // {
          dependencies = [
            sources."JSONStream-0.4.4"
            sources."duplexer-0.0.4"
            sources."through-2.2.7"
          ];
        })
      sources."interpolate-0.1.0"
      sources."interpret-1.1.0"
      sources."is-absolute-1.0.0"
      sources."is-core-module-2.11.0"
      sources."is-extglob-2.1.1"
      sources."is-glob-4.0.3"
      sources."is-number-7.0.0"
      sources."is-plain-object-2.0.4"
      sources."is-relative-1.0.0"
      sources."is-unc-path-1.0.0"
      sources."is-what-3.14.1"
      sources."is-windows-1.0.2"
      sources."isarray-0.0.1"
      sources."isexe-2.0.0"
      sources."isobject-3.0.1"
      sources."js-yaml-3.14.1"
      sources."jshint-2.13.6"
      sources."jsonify-0.0.1"
      sources."jsonparse-0.0.5"
      sources."kind-of-6.0.3"
      sources."less-4.1.3"
      sources."lexical-scope-0.0.15"
      (sources."liftup-3.0.1"
        // {
          dependencies = [
            sources."findup-sync-4.0.0"
          ];
        })
      sources."livereload-js-2.4.0"
      sources."lodash-4.17.21"
      sources."make-dir-2.1.0"
      sources."make-iterator-1.0.1"
      sources."map-cache-0.2.2"
      sources."micromatch-4.0.5"
      sources."mime-1.6.0"
      sources."minimatch-3.0.8"
      sources."minimist-0.0.10"
      sources."mkdirp-1.0.4"
      (sources."module-deps-1.1.0"
        // {
          dependencies = [
            sources."resolve-0.6.3"
          ];
        })
      sources."ms-2.1.3"
      (sources."needle-3.2.0"
        // {
          dependencies = [
            sources."iconv-lite-0.6.3"
          ];
        })
      sources."nopt-3.0.6"
      sources."object-assign-4.1.1"
      sources."object-inspect-1.12.2"
      sources."object.defaults-1.1.0"
      sources."object.map-1.0.1"
      sources."object.pick-1.3.0"
      sources."once-1.4.0"
      sources."optimist-0.5.2"
      sources."os-browserify-0.1.2"
      sources."os-homedir-1.0.2"
      sources."os-tmpdir-1.0.2"
      sources."osenv-0.1.5"
      sources."parents-0.0.3"
      sources."parse-filepath-1.0.2"
      sources."parse-node-version-1.0.1"
      sources."parse-passwd-1.0.0"
      sources."path-is-absolute-1.0.1"
      sources."path-parse-1.0.7"
      sources."path-platform-0.0.1"
      sources."path-root-0.1.1"
      sources."path-root-regex-0.1.2"
      sources."pica-1.1.1"
      sources."picomatch-2.3.1"
      sources."pify-4.0.1"
      sources."process-0.5.2"
      sources."prr-1.0.1"
      sources."punycode-1.2.4"
      sources."qs-6.11.0"
      sources."raw-body-1.1.7"
      sources."readable-stream-1.1.14"
      sources."rechoir-0.7.1"
      sources."resolve-1.22.1"
      sources."resolve-dir-1.0.1"
      (sources."rfile-1.0.0"
        // {
          dependencies = [
            sources."resolve-0.3.1"
          ];
        })
      sources."rimraf-3.0.2"
      (sources."ruglify-1.0.0"
        // {
          dependencies = [
            sources."optimist-0.3.7"
            sources."source-map-0.1.43"
            sources."uglify-js-2.2.5"
          ];
        })
      sources."safe-buffer-5.2.1"
      sources."safe-json-parse-1.0.1"
      sources."safer-buffer-2.1.2"
      sources."sax-1.2.4"
      sources."semver-5.7.1"
      sources."shell-quote-0.0.1"
      sources."side-channel-1.0.4"
      sources."source-map-0.6.1"
      sources."sprintf-js-1.1.2"
      sources."stream-combiner-0.0.4"
      sources."string-template-0.2.1"
      sources."string_decoder-0.10.31"
      sources."strip-json-comments-1.0.4"
      sources."supports-color-7.2.0"
      sources."supports-preserve-symlinks-flag-1.0.0"
      (sources."syntax-error-0.0.1"
        // {
          dependencies = [
            sources."esprima-0.9.9"
          ];
        })
      (sources."tape-0.2.2"
        // {
          dependencies = [
            sources."deep-equal-0.0.0"
          ];
        })
      sources."through-2.3.8"
      sources."tiny-lr-1.1.1"
      sources."to-regex-range-5.0.1"
      sources."to-utf8-0.0.1"
      sources."tslib-2.4.1"
      (sources."uglify-js-2.4.24"
        // {
          dependencies = [
            sources."async-0.2.10"
            sources."source-map-0.1.34"
          ];
        })
      sources."uglify-to-browserify-1.0.2"
      sources."umd-1.3.1"
      sources."unc-path-regex-0.1.2"
      sources."underscore.string-3.3.6"
      sources."util-deprecate-1.0.2"
      sources."v8flags-3.2.0"
      sources."vm-browserify-0.0.4"
      sources."vtf-0.0.3"
      sources."websocket-driver-0.7.4"
      sources."websocket-extensions-0.1.4"
      sources."webworkify-1.0.2"
      sources."which-1.3.1"
      sources."window-size-0.1.0"
      sources."wordwrap-0.0.3"
      sources."wrappy-1.0.2"
      (sources."yargs-3.5.4"
        // {
          dependencies = [
            sources."wordwrap-0.0.2"
          ];
        })
      sources."zlib-browserify-0.0.3"
    ];
    buildInputs = globalBuildInputs;
    meta = {
      description = "Make TF2 sprays in the browser";
    };
    production = false;
    bypassCache = true;
    reconstructLock = false;
  };
in {
  args = args;
  sources = sources;
  tarball = nodeEnv.buildNodeSourceDist args;
  package = nodeEnv.buildNodePackage args;
  shell = nodeEnv.buildNodeShell args;
  nodeDependencies = nodeEnv.buildNodeDependencies (lib.overrideExisting args {
    src = stdenv.mkDerivation {
      name = args.name + "-package-json";
      src =
        nix-gitignore.gitignoreSourcePure [
          "*"
          "!package.json"
          "!package-lock.json"
        ]
        args.src;
      dontBuild = true;
      installPhase = "mkdir -p $out; cp -r ./* $out;";
    };
  });
}
